import type { PriceHistory, ProductVariant, SupplierProduct } from '../crm/types'

interface ParserMockSeed {
  productId: string
  variantId: string
  supplierId: string
  externalId: string
  sku: string
  name: string
  category: string
  description: string
  unit: string
  basePurchasePrice: number
  availability: string
  imageUrl: string
  sourceUrl: string
  variantName: string
  size: string
  color: string
  material: string
  lastSeenAt: string
}

const parserMockSeeds: ParserMockSeed[] = [
  {
    "productId": "prod-invakor-2268096",
    "variantId": "var-invakor-2268096",
    "supplierId": "sup-invakor",
    "externalId": "2268096",
    "sku": "2268096",
    "name": "Мнемосхема тактильная ПВХ 3 мм Эконом Размер 610х470мм",
    "category": "Мнемосхемы",
    "description": "Мнемосхемы. Мнемосхемы для помещений. Эконом. Размер: 610×470мм",
    "unit": "шт",
    "basePurchasePrice": 9020,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/2268096.jpg",
    "sourceUrl": "https://invakor.ru/store/taktilnye-tablichki-vyveski/mnemoshemy/mnemoshemy-dlya-pomescheniy/ekonom/mnemoshema-taktilnaya-pvh-3-mm-ekonom-razmer-610h470mm",
    "variantName": "610×470мм",
    "size": "610×470мм",
    "color": "по карточке",
    "material": "ПВХ",
    "lastSeenAt": "2026-06-26T11:17:52+00:00"
  },
  {
    "productId": "prod-invakor-2266341",
    "variantId": "var-invakor-2266341",
    "supplierId": "sup-invakor",
    "externalId": "2266341",
    "sku": "2266341",
    "name": "Мнемосхема тактильная полноцветная композит 4мм с защитным покрытием. Размер 600х800мм",
    "category": "Мнемосхемы",
    "description": "Мнемосхемы. Мнемосхемы для помещений. Композит. Размер: 600×800мм",
    "unit": "шт",
    "basePurchasePrice": 21890,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/2266341.jpg",
    "sourceUrl": "https://invakor.ru/store/taktilnye-tablichki-vyveski/mnemoshemy/mnemoshemy-dlya-pomescheniy/kompozit/mnemoshema-taktilnaya-polnocvetnaya-kompozit-4mm-s-zaschitnym-2",
    "variantName": "600×800мм",
    "size": "600×800мм",
    "color": "по карточке",
    "material": "композит",
    "lastSeenAt": "2026-06-26T11:17:55+00:00"
  },
  {
    "productId": "prod-invakor-2268128",
    "variantId": "var-invakor-2268128",
    "supplierId": "sup-invakor",
    "externalId": "2268128",
    "sku": "2268128",
    "name": "Мнемосхема тактильно-звуковая с текстовым табло и индукционной петлей",
    "category": "Мнемосхемы",
    "description": "Мнемосхемы. Тактильно-звуковые мнемосхемы",
    "unit": "шт",
    "basePurchasePrice": 212190,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/2268128.jpg",
    "sourceUrl": "https://invakor.ru/store/taktilnye-tablichki-vyveski/mnemoshemy/taktilno-zvukovye-mnemoshemy/mnemoshema-taktilno-zvukovaya-s-tekstovym-tablo-i-indukcionno",
    "variantName": "Мнемосхема тактильно-звуковая с текстовым табло и индукционной петлей",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T11:19:08+00:00"
  },
  {
    "productId": "prod-invakor-3377776",
    "variantId": "var-invakor-3377776",
    "supplierId": "sup-invakor",
    "externalId": "3377776",
    "sku": "3377776",
    "name": "Настенная тактильно-звуковая мнемосхема со встроенной индукционной системой и интегрированной кнопкой вызова помощи",
    "category": "Мнемосхемы",
    "description": "Мнемосхемы. Тактильно-звуковые мнемосхемы",
    "unit": "шт",
    "basePurchasePrice": 203280,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/3377776.jpg",
    "sourceUrl": "https://invakor.ru/store/taktilnye-tablichki-vyveski/mnemoshemy/taktilno-zvukovye-mnemoshemy/nastennaya-taktilno-zvukovaya-mnemoskhema-so-vstroennoy-induk",
    "variantName": "Настенная тактильно-звуковая мнемосхема со встроенной индукционной системой и интегрированной кнопкой вызова помощи",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T11:19:08+00:00"
  },
  {
    "productId": "prod-invakor-3377782",
    "variantId": "var-invakor-3377782",
    "supplierId": "sup-invakor",
    "externalId": "3377782",
    "sku": "3377782",
    "name": "Табличка комплексная ПВХ с интегрированной кнопкой вызова помощи и прямым креплением 480х380 мм (комплект)",
    "category": "Таблички с кнопкой вызова помощи",
    "description": "Таблички с кнопкой вызова помощи. Размер: 480×380 мм",
    "unit": "шт",
    "basePurchasePrice": 12320,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/3377782.jpg",
    "sourceUrl": "https://invakor.ru/store/taktilnye-tablichki-vyveski/tablichka-s-knopkoy-vyzova-pomoschi/tablichka-kompleksnaya-pvh-s-integrirovannoy-knopkoy-vyzova-p",
    "variantName": "480×380 мм",
    "size": "480×380 мм",
    "color": "по карточке",
    "material": "ПВХ",
    "lastSeenAt": "2026-06-26T11:21:17+00:00"
  },
  {
    "productId": "prod-invakor-2292858",
    "variantId": "var-invakor-2292858",
    "supplierId": "sup-invakor",
    "externalId": "2292858",
    "sku": "2292858",
    "name": "Комплексная тактильная табличка композит 4мм Размер 100x300мм",
    "category": "Информационные таблички",
    "description": "Информационные таблички. Комплексные. Размер: 100×300мм",
    "unit": "шт",
    "basePurchasePrice": 1210,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/2292858.jpg",
    "sourceUrl": "https://invakor.ru/store/taktilnye-tablichki-vyveski/tablichki-na-kabinety/kompleksnye/kompleksnaya-taktilnaya-tablichka-kompozit-4mm-razmer-100x300",
    "variantName": "100×300мм",
    "size": "100×300мм",
    "color": "по карточке",
    "material": "композит",
    "lastSeenAt": "2026-06-26T11:19:22+00:00"
  },
  {
    "productId": "prod-invakor-2292900",
    "variantId": "var-invakor-2292900",
    "supplierId": "sup-invakor",
    "externalId": "2292900",
    "sku": "2292900",
    "name": "Тактильная табличка Брайлем (монохром) ПВХ 3 мм. Размер 100 х 300 мм",
    "category": "Информационные таблички",
    "description": "Информационные таблички. С брайлем. Размер: 100 × 300 мм",
    "unit": "шт",
    "basePurchasePrice": 880,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/2292900.jpg",
    "sourceUrl": "https://invakor.ru/store/taktilnye-tablichki-vyveski/tablichki-na-kabinety/s-braylem/taktilnaya-tablichka-braylem-monohrom-pvh-3-mm-razmer-100-h-3",
    "variantName": "100 × 300 мм",
    "size": "100 × 300 мм",
    "color": "по карточке",
    "material": "ПВХ",
    "lastSeenAt": "2026-06-26T11:19:23+00:00"
  },
  {
    "productId": "prod-invakor-2276973",
    "variantId": "var-invakor-2276973",
    "supplierId": "sup-invakor",
    "externalId": "2276973",
    "sku": "2276973",
    "name": "Тактильная пиктограмма с покрытием с брайлем 160х200мм",
    "category": "Пиктограммы",
    "description": "Пиктограммы. Пиктограммы с покрытием. Размер: 160×200мм",
    "unit": "шт",
    "basePurchasePrice": 1529,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/2276973.jpg",
    "sourceUrl": "https://invakor.ru/store/taktilnye-tablichki-vyveski/piktogrammy/piktogrammy-s-pokrytiem/taktilnaya-piktogramma-s-pokrytiem-s-braylem-160h200mm",
    "variantName": "160×200мм",
    "size": "160×200мм",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T11:19:12+00:00"
  },
  {
    "productId": "prod-invakor-2274207",
    "variantId": "var-invakor-2274207",
    "supplierId": "sup-invakor",
    "externalId": "2274207",
    "sku": "2274207",
    "name": "Тактильная кнопка вызова помощи персонала",
    "category": "Кнопки вызова персонала",
    "description": "Кнопки вызова персонала",
    "unit": "шт",
    "basePurchasePrice": 1100,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/2274207.jpg",
    "sourceUrl": "https://invakor.ru/store/sistemy-vyzova-personala/knopki-vyzova-personala-opoveschateli/taktilnaya-knopka-vyzova-pomoschi-personala",
    "variantName": "Тактильная кнопка вызова помощи персонала",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T11:20:59+00:00"
  },
  {
    "productId": "prod-invakor-3377806",
    "variantId": "var-invakor-3377806",
    "supplierId": "sup-invakor",
    "externalId": "3377806",
    "sku": "3377806",
    "name": "Кнопка вызова персонала ГОСТ, антивандальная, c питанием 220V",
    "category": "Кнопки вызова персонала",
    "description": "Кнопки вызова персонала",
    "unit": "шт",
    "basePurchasePrice": 10890,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/3377806.jpg",
    "sourceUrl": "https://invakor.ru/store/sistemy-vyzova-personala/knopki-vyzova-personala-opoveschateli/knopka-vyzova-personala-gost-antivandalnaya-c-pitaniem-220v",
    "variantName": "Кнопка вызова персонала ГОСТ, антивандальная, c питанием 220V",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T11:20:59+00:00"
  },
  {
    "productId": "prod-invakor-2277013",
    "variantId": "var-invakor-2277013",
    "supplierId": "sup-invakor",
    "externalId": "2277013",
    "sku": "2277013",
    "name": "Портативная индукционная система \"VERT-1a мини\"",
    "category": "Портативные индукционные системы",
    "description": "Портативные индукционные системы",
    "unit": "шт",
    "basePurchasePrice": 18700,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/2277013.jpg",
    "sourceUrl": "https://invakor.ru/store/indukcionnye-sistemy-i-petli/portativnye-indukcionnye-sistemy/indukcionnaya-portativnaya-sistema-invakor-mini-mp3",
    "variantName": "Портативная индукционная система \"VERT-1a мини\"",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T11:20:02+00:00"
  },
  {
    "productId": "prod-invakor-2277017",
    "variantId": "var-invakor-2277017",
    "supplierId": "sup-invakor",
    "externalId": "2277017",
    "sku": "2277017",
    "name": "Индукционная система «Eco Sound»",
    "category": "Портативные индукционные системы",
    "description": "Портативные индукционные системы",
    "unit": "шт",
    "basePurchasePrice": 9900,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/2277017.jpg",
    "sourceUrl": "https://invakor.ru/store/indukcionnye-sistemy-i-petli/portativnye-indukcionnye-sistemy/indukcionnaya-sistema-eco-sound",
    "variantName": "Индукционная система «Eco Sound»",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T11:20:03+00:00"
  },
  {
    "productId": "prod-invakor-3169209",
    "variantId": "var-invakor-3169209",
    "supplierId": "sup-invakor",
    "externalId": "3169209",
    "sku": "3169209",
    "name": "Маяк светозвуковой «Привод-2»",
    "category": "Визуально-акустическое табло для инвалидов",
    "description": "Визуально-акустическое табло для инвалидов",
    "unit": "шт",
    "basePurchasePrice": 51717,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/3169209.png",
    "sourceUrl": "https://invakor.ru/store/beguschie-stroki/vizualno-akusticheskoe-tablo-dlya-invalidov/mayak-svetozvukovoy-privod-2",
    "variantName": "Маяк светозвуковой «Привод-2»",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T11:19:53+00:00"
  },
  {
    "productId": "prod-invakor-2292919",
    "variantId": "var-invakor-2292919",
    "supplierId": "sup-invakor",
    "externalId": "2292919",
    "sku": "2292919",
    "name": "Звуковой указатель полистирол, 300 x 150 x 25мм",
    "category": "Информационные таблички",
    "description": "Информационные таблички. Звуковые, со сменной информацией. Размер: 300 × 150 × 25мм",
    "unit": "шт",
    "basePurchasePrice": 4290,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/2292919.jpg",
    "sourceUrl": "https://invakor.ru/store/taktilnye-tablichki-vyveski/tablichki-na-kabinety/zvukovye-so-smennoy-informaciey/zvukovoy-ukazatel-polistirol-300-x-150-x-25mm",
    "variantName": "300 × 150 × 25мм",
    "size": "300 × 150 × 25мм",
    "color": "по карточке",
    "material": "полистирол",
    "lastSeenAt": "2026-06-26T11:19:24+00:00"
  },
  {
    "productId": "prod-invakor-3377799",
    "variantId": "var-invakor-3377799",
    "supplierId": "sup-invakor",
    "externalId": "3377799",
    "sku": "3377799",
    "name": "Плитка тактильная контрастная из полиуретана , со сменными рифами (направление движения) ГОСТ",
    "category": "Тактильная плитка, клей",
    "description": "Тактильная плитка, клей",
    "unit": "шт",
    "basePurchasePrice": 275,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/3377799.png",
    "sourceUrl": "https://invakor.ru/store/taktilno-vizualnye-znaki-dostupnosti/taktilnaya-plitka/gost-new-2021-plitka-taktilnaya-kontrastnaya-iz-poliuretana-s-3",
    "variantName": "Плитка тактильная контрастная из полиуретана , со сменными рифами (направление движения) ГОСТ",
    "size": "по карточке",
    "color": "по карточке",
    "material": "полиуретан",
    "lastSeenAt": "2026-06-26T11:21:09+00:00"
  },
  {
    "productId": "prod-invakor-2664508",
    "variantId": "var-invakor-2664508",
    "supplierId": "sup-invakor",
    "externalId": "2664508",
    "sku": "2664508",
    "name": "Тактильная плитка ПВХ, жёлтая (конус в шахматном порядке) 300 x 300 мм",
    "category": "Тактильная плитка, клей",
    "description": "Тактильная плитка, клей. Размер: 300 × 300 мм",
    "unit": "шт",
    "basePurchasePrice": 275,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/2664508.jpg",
    "sourceUrl": "https://invakor.ru/store/taktilno-vizualnye-znaki-dostupnosti/taktilnaya-plitka/taktilnaya-plitka-pvh-zheltaya-konus-v-shahmatnom-poryadke-30",
    "variantName": "300 × 300 мм",
    "size": "300 × 300 мм",
    "color": "желтый",
    "material": "ПВХ",
    "lastSeenAt": "2026-06-26T11:21:09+00:00"
  },
  {
    "productId": "prod-invakor-4434637",
    "variantId": "var-invakor-4434637",
    "supplierId": "sup-invakor",
    "externalId": "4434637",
    "sku": "4434637",
    "name": "Полоса тактильная, комбинированная, с противоскользящей вставкой, без штифта, 4х35х290, H-4мм, I-0мм, AL/PL, желтый",
    "category": "Тактильные индикаторы",
    "description": "Тактильные индикаторы. Комбинированные. Размер: 4×35×290",
    "unit": "шт",
    "basePurchasePrice": 372,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/4434637.png",
    "sourceUrl": "https://invakor.ru/store/taktilno-vizualnye-znaki-dostupnosti/taktilnye-indikatory/kombinirovannye/polosa-taktilnaya-kombinirovannaya-s-protivoskolzyaschey-vsta-2",
    "variantName": "4×35×290",
    "size": "4×35×290",
    "color": "желтый",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T11:18:52+00:00"
  },
  {
    "productId": "prod-invakor-4434643",
    "variantId": "var-invakor-4434643",
    "supplierId": "sup-invakor",
    "externalId": "4434643",
    "sku": "4434643",
    "name": "Конус тактильный, комбинированный, с противоскользящей вставкой, М7, без штифта, D35x35, H-4мм, I-0мм, AL/PL, желтый",
    "category": "Тактильные индикаторы",
    "description": "Тактильные индикаторы. Комбинированные. Размер: D35×35",
    "unit": "шт",
    "basePurchasePrice": 116,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/4434643.png",
    "sourceUrl": "https://invakor.ru/store/taktilno-vizualnye-znaki-dostupnosti/taktilnye-indikatory/kombinirovannye/konus-taktilnyy-kombinirovannyy-s-protivoskolzyaschey-vstavko-2",
    "variantName": "D35×35",
    "size": "D35×35",
    "color": "желтый",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T11:18:52+00:00"
  },
  {
    "productId": "prod-invakor-1965760",
    "variantId": "var-invakor-1965760",
    "supplierId": "sup-invakor",
    "externalId": "1965760",
    "sku": "1965760",
    "name": "Рампа складная 2х секционная KR 307-6",
    "category": "Рампы складные для инвалидов",
    "description": "Рампы складные для инвалидов",
    "unit": "шт",
    "basePurchasePrice": 15510,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/1965760.jpg",
    "sourceUrl": "https://invakor.ru/store/pandusy/rampy-skladnye-dlya-invalidov/pandus-skladnoy-2h-sekcionnyy-307-6",
    "variantName": "Рампа складная 2х секционная KR 307-6",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T11:20:31+00:00"
  },
  {
    "productId": "prod-invakor-2271040",
    "variantId": "var-invakor-2271040",
    "supplierId": "sup-invakor",
    "externalId": "2271040",
    "sku": "2271040",
    "name": "Поручень настенный откидной 600мм",
    "category": "Антибактериальные",
    "description": "Антибактериальные. Размер: 600мм",
    "unit": "шт",
    "basePurchasePrice": 3900,
    "availability": "в наличии",
    "imageUrl": "/mock/parser-products/invakor/2271040.jpg",
    "sourceUrl": "https://invakor.ru/store/poruchni/antibakterialnye/poruchen-nastennyy-otkidnoy-antibakterialnyy-600mm",
    "variantName": "600мм",
    "size": "600мм",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T11:20:40+00:00"
  },
  {
    "productId": "prod-istok-audio-universalnaya-knopka-s-shirokoy-zonoy-nazhatiya",
    "variantId": "var-istok-audio-universalnaya-knopka-s-shirokoy-zonoy-nazhatiya",
    "supplierId": "sup-istok-audio",
    "externalId": "universalnaya-knopka-s-shirokoy-zonoy-nazhatiya",
    "sku": "universalnaya-knopka-s-shirokoy-zonoy-nazhatiya",
    "name": "Кнопка вызова УНИВЕРСАЛ (Аа)",
    "category": "Системы вызова помощника",
    "description": "Системы вызова помощника",
    "unit": "шт",
    "basePurchasePrice": 9800,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/universalnaya-knopka-s-shirokoy-zonoy-nazhatiya.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/universalnaya-knopka-s-shirokoy-zonoy-nazhatiya",
    "variantName": "Кнопка вызова УНИВЕРСАЛ (Аа)",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:15:02+00:00"
  },
  {
    "productId": "prod-istok-audio-knopka-vyzova-personala-universalnaya-so-shnurkom-av",
    "variantId": "var-istok-audio-knopka-vyzova-personala-universalnaya-so-shnurkom-av",
    "supplierId": "sup-istok-audio",
    "externalId": "knopka-vyzova-personala-universalnaya-so-shnurkom-av",
    "sku": "knopka-vyzova-personala-universalnaya-so-shnurkom-av",
    "name": "Кнопка вызова УНИВЕРСАЛ со шнурком (Ав)",
    "category": "Системы вызова помощника",
    "description": "Системы вызова помощника",
    "unit": "шт",
    "basePurchasePrice": 11500,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/knopka-vyzova-personala-universalnaya-so-shnurkom-av.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/knopka-vyzova-personala-universalnaya-so-shnurkom-av",
    "variantName": "Кнопка вызова УНИВЕРСАЛ со шнурком (Ав)",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:15:02+00:00"
  },
  {
    "productId": "prod-istok-audio-knopka_vyzova_antivandalnaya_vsepogodnaya_so_shnurkom_vynosnoy_svetozvukovoy_opoveshchatel",
    "variantId": "var-istok-audio-knopka_vyzova_antivandalnaya_vsepogodnaya_so_shnurkom_vynosnoy_svetozvukovoy_opoveshchatel",
    "supplierId": "sup-istok-audio",
    "externalId": "knopka_vyzova_antivandalnaya_vsepogodnaya_so_shnurkom_vynosnoy_svetozvukovoy_opoveshchatel",
    "sku": "knopka_vyzova_antivandalnaya_vsepogodnaya_so_shnurkom_vynosnoy_svetozvukovoy_opoveshchatel",
    "name": "Кнопка вызова со шнурком + выносной светозвуковой оповещатель (Ау)",
    "category": "Системы вызова помощника",
    "description": "Системы вызова помощника",
    "unit": "шт",
    "basePurchasePrice": 16400,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/knopka_vyzova_antivandalnaya_vsepogodnaya_so_shnurkom_vynosnoy_svetozvukovoy_opoveshchatel.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/knopka_vyzova_antivandalnaya_vsepogodnaya_so_shnurkom_vynosnoy_svetozvukovoy_opoveshchatel",
    "variantName": "Кнопка вызова со шнурком + выносной светозвуковой оповещатель (Ау)",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:15:02+00:00"
  },
  {
    "productId": "prod-istok-audio-statsionarnyy-priemnik-s-zhk-displeem",
    "variantId": "var-istok-audio-statsionarnyy-priemnik-s-zhk-displeem",
    "supplierId": "sup-istok-audio",
    "externalId": "statsionarnyy-priemnik-s-zhk-displeem",
    "sku": "statsionarnyy-priemnik-s-zhk-displeem",
    "name": "Приемник настольный (Сп)",
    "category": "Системы вызова помощника",
    "description": "Системы вызова помощника",
    "unit": "шт",
    "basePurchasePrice": 12900,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/statsionarnyy-priemnik-s-zhk-displeem.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/statsionarnyy-priemnik-s-zhk-displeem",
    "variantName": "Приемник настольный (Сп)",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:15:02+00:00"
  },
  {
    "productId": "prod-istok-audio-perenosnoy-priemnik-s-zhk-displeem",
    "variantId": "var-istok-audio-perenosnoy-priemnik-s-zhk-displeem",
    "supplierId": "sup-istok-audio",
    "externalId": "perenosnoy-priemnik-s-zhk-displeem",
    "sku": "perenosnoy-priemnik-s-zhk-displeem",
    "name": "Переносной приемник с ЖК-дисплеем (Мз)",
    "category": "Системы вызова помощника",
    "description": "Системы вызова помощника",
    "unit": "шт",
    "basePurchasePrice": 10800,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/perenosnoy-priemnik-s-zhk-displeem.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/perenosnoy-priemnik-s-zhk-displeem",
    "variantName": "Переносной приемник с ЖК-дисплеем (Мз)",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:15:02+00:00"
  },
  {
    "productId": "prod-istok-audio-pulsar_so_zvukovym_opoveshcheniem",
    "variantId": "var-istok-audio-pulsar_so_zvukovym_opoveshcheniem",
    "supplierId": "sup-istok-audio",
    "externalId": "pulsar_so_zvukovym_opoveshcheniem",
    "sku": "pulsar_so_zvukovym_opoveshcheniem",
    "name": "Беспроводная система вызова помощника со звуковым оповещением",
    "category": "Системы вызова помощника",
    "description": "Системы вызова помощника",
    "unit": "шт",
    "basePurchasePrice": 31500,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/pulsar_so_zvukovym_opoveshcheniem.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/pulsar_so_zvukovym_opoveshcheniem",
    "variantName": "Беспроводная система вызова помощника со звуковым оповещением",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:15:02+00:00"
  },
  {
    "productId": "prod-istok-audio-stoyka_dlya_knopki_vyzova",
    "variantId": "var-istok-audio-stoyka_dlya_knopki_vyzova",
    "supplierId": "sup-istok-audio",
    "externalId": "stoyka_dlya_knopki_vyzova",
    "sku": "stoyka_dlya_knopki_vyzova",
    "name": "Стойка для кнопки вызова",
    "category": "Системы вызова помощника",
    "description": "Системы вызова помощника",
    "unit": "шт",
    "basePurchasePrice": 5200,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/stoyka_dlya_knopki_vyzova.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/stoyka_dlya_knopki_vyzova",
    "variantName": "Стойка для кнопки вызова",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:15:02+00:00"
  },
  {
    "productId": "prod-istok-audio-znak_dostupnosti_dlya_invalidov_vsekh_kategoriy",
    "variantId": "var-istok-audio-znak_dostupnosti_dlya_invalidov_vsekh_kategoriy",
    "supplierId": "sup-istok-audio",
    "externalId": "znak_dostupnosti_dlya_invalidov_vsekh_kategoriy",
    "sku": "znak_dostupnosti_dlya_invalidov_vsekh_kategoriy",
    "name": "Знак доступности для инвалидов всех категорий",
    "category": "Тактильно-визуальные знаки доступности",
    "description": "Тактильно-визуальные знаки доступности. Знаки доступности",
    "unit": "шт",
    "basePurchasePrice": 780,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/znak_dostupnosti_dlya_invalidov_vsekh_kategoriy.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/znak_dostupnosti_dlya_invalidov_vsekh_kategoriy",
    "variantName": "Знак доступности для инвалидов всех категорий",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:06:19+00:00"
  },
  {
    "productId": "prod-istok-audio-taktilnyy_znak_dostupnost_dlya_invalidov_vsekh_kategoriy",
    "variantId": "var-istok-audio-taktilnyy_znak_dostupnost_dlya_invalidov_vsekh_kategoriy",
    "supplierId": "sup-istok-audio",
    "externalId": "taktilnyy_znak_dostupnost_dlya_invalidov_vsekh_kategoriy",
    "sku": "taktilnyy_znak_dostupnost_dlya_invalidov_vsekh_kategoriy",
    "name": "Доступность для инвалидов всех категорий — тактильный знак",
    "category": "Тактильно-визуальные знаки доступности",
    "description": "Тактильно-визуальные знаки доступности. Знаки доступности",
    "unit": "шт",
    "basePurchasePrice": 1250,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/taktilnyy_znak_dostupnost_dlya_invalidov_vsekh_kategoriy.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/taktilnyy_znak_dostupnost_dlya_invalidov_vsekh_kategoriy",
    "variantName": "Доступность для инвалидов всех категорий — тактильный знак",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:06:19+00:00"
  },
  {
    "productId": "prod-istok-audio-taktilnyy_znak_tualet_dlya_invalidov",
    "variantId": "var-istok-audio-taktilnyy_znak_tualet_dlya_invalidov",
    "supplierId": "sup-istok-audio",
    "externalId": "taktilnyy_znak_tualet_dlya_invalidov",
    "sku": "taktilnyy_znak_tualet_dlya_invalidov",
    "name": "Туалет для инвалидов — тактильный знак",
    "category": "Тактильно-визуальные знаки доступности",
    "description": "Тактильно-визуальные знаки доступности. Информационные знаки. index.php",
    "unit": "шт",
    "basePurchasePrice": 1250,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/taktilnyy_znak_tualet_dlya_invalidov.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/taktilnyy_znak_tualet_dlya_invalidov",
    "variantName": "Туалет для инвалидов — тактильный знак",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:06:26+00:00"
  },
  {
    "productId": "prod-istok-audio-taktilnyy_znak_knopka_vyzova",
    "variantId": "var-istok-audio-taktilnyy_znak_knopka_vyzova",
    "supplierId": "sup-istok-audio",
    "externalId": "taktilnyy_znak_knopka_vyzova",
    "sku": "taktilnyy_znak_knopka_vyzova",
    "name": "Тактильный знак «Кнопка вызова»",
    "category": "Тактильно-визуальные знаки доступности",
    "description": "Тактильно-визуальные знаки доступности. Информационные знаки. index.php",
    "unit": "шт",
    "basePurchasePrice": 1250,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/taktilnyy_znak_knopka_vyzova.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/taktilnyy_znak_knopka_vyzova",
    "variantName": "Тактильный знак «Кнопка вызова»",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:06:26+00:00"
  },
  {
    "productId": "prod-istok-audio-informatsionno_taktilnyy_znak_tablichka_300kh200_mm",
    "variantId": "var-istok-audio-informatsionno_taktilnyy_znak_tablichka_300kh200_mm",
    "supplierId": "sup-istok-audio",
    "externalId": "informatsionno_taktilnyy_znak_tablichka_300kh200_mm",
    "sku": "informatsionno_taktilnyy_znak_tablichka_300kh200_mm",
    "name": "Информационно-тактильный знак (табличка), рельефный, пластик 300х200 мм",
    "category": "Тактильно-визуальные знаки доступности",
    "description": "Тактильно-визуальные знаки доступности. Информационные табло и таблички",
    "unit": "шт",
    "basePurchasePrice": 1900,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/informatsionno_taktilnyy_znak_tablichka_300kh200_mm.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/informatsionno_taktilnyy_znak_tablichka_300kh200_mm",
    "variantName": "300х200мм",
    "size": "300х200мм",
    "color": "по карточке",
    "material": "пластик",
    "lastSeenAt": "2026-06-26T10:06:20+00:00"
  },
  {
    "productId": "prod-istok-audio-taktilno_zvukovaya_mnemoskhema_610kh470_s_naklonnoy_stoykoy",
    "variantId": "var-istok-audio-taktilno_zvukovaya_mnemoskhema_610kh470_s_naklonnoy_stoykoy",
    "supplierId": "sup-istok-audio",
    "externalId": "taktilno_zvukovaya_mnemoskhema_610kh470_s_naklonnoy_stoykoy",
    "sku": "taktilno_zvukovaya_mnemoskhema_610kh470_s_naklonnoy_stoykoy",
    "name": "Тактильно-звуковая мнемосхема 610х470 мм с наклонной стойкой",
    "category": "Тактильно-визуальные знаки доступности",
    "description": "Тактильно-визуальные знаки доступности. Тактильные рельефные мнемосхемы",
    "unit": "шт",
    "basePurchasePrice": 78000,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/taktilno_zvukovaya_mnemoskhema_610kh470_s_naklonnoy_stoykoy.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/taktilno_zvukovaya_mnemoskhema_610kh470_s_naklonnoy_stoykoy",
    "variantName": "610х470мм",
    "size": "610х470мм",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:06:20+00:00"
  },
  {
    "productId": "prod-istok-audio-svetonakopitelnaya_mnemoskhema_800kh600_mm",
    "variantId": "var-istok-audio-svetonakopitelnaya_mnemoskhema_800kh600_mm",
    "supplierId": "sup-istok-audio",
    "externalId": "svetonakopitelnaya_mnemoskhema_800kh600_mm",
    "sku": "svetonakopitelnaya_mnemoskhema_800kh600_mm",
    "name": "Светонакопительная мнемосхема 800х600 мм",
    "category": "Тактильно-визуальные знаки доступности",
    "description": "Тактильно-визуальные знаки доступности. Тактильные рельефные мнемосхемы",
    "unit": "шт",
    "basePurchasePrice": 42000,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/svetonakopitelnaya_mnemoskhema_800kh600_mm.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/svetonakopitelnaya_mnemoskhema_800kh600_mm",
    "variantName": "800х600мм",
    "size": "800х600мм",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:06:20+00:00"
  },
  {
    "productId": "prod-istok-audio-begushchaya_stroka_ulitsa_pomeshchenie_1010kh210kh90_krasnaya",
    "variantId": "var-istok-audio-begushchaya_stroka_ulitsa_pomeshchenie_1010kh210kh90_krasnaya",
    "supplierId": "sup-istok-audio",
    "externalId": "begushchaya_stroka_ulitsa_pomeshchenie_1010kh210kh90_krasnaya",
    "sku": "begushchaya_stroka_ulitsa_pomeshchenie_1010kh210kh90_krasnaya",
    "name": "Бегущая строка улица/помещение 1010х210х90, красная",
    "category": "Бегущие строки",
    "description": "Бегущие строки",
    "unit": "шт",
    "basePurchasePrice": 38500,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/begushchaya_stroka_ulitsa_pomeshchenie_1010kh210kh90_krasnaya.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/begushchaya_stroka_ulitsa_pomeshchenie_1010kh210kh90_krasnaya",
    "variantName": "1010х210х90",
    "size": "1010х210х90",
    "color": "красный",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:15:02+00:00"
  },
  {
    "productId": "prod-istok-audio-vertikalnyy_podemnik_dlya_invalidov_ekonom_variant",
    "variantId": "var-istok-audio-vertikalnyy_podemnik_dlya_invalidov_ekonom_variant",
    "supplierId": "sup-istok-audio",
    "externalId": "vertikalnyy_podemnik_dlya_invalidov_ekonom_variant",
    "sku": "vertikalnyy_podemnik_dlya_invalidov_ekonom_variant",
    "name": "Вертикальный подъемник для инвалидов. Эконом-вариант",
    "category": "Подъемники",
    "description": "Подъемники. Вертикальные подъемники",
    "unit": "шт",
    "basePurchasePrice": 640000,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/vertikalnyy_podemnik_dlya_invalidov_ekonom_variant.webp",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/vertikalnyy_podemnik_dlya_invalidov_ekonom_variant",
    "variantName": "Вертикальный подъемник для инвалидов. Эконом-вариант",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:06:17+00:00"
  },
  {
    "productId": "prod-istok-audio-tualetnaya_kabina_ecogr_universal_na_baze_ecostyle_",
    "variantId": "var-istok-audio-tualetnaya_kabina_ecogr_universal_na_baze_ecostyle_",
    "supplierId": "sup-istok-audio",
    "externalId": "tualetnaya_kabina_ecogr_universal_na_baze_ecostyle_",
    "sku": "tualetnaya_kabina_ecogr_universal_na_baze_ecostyle_",
    "name": "Туалетная кабина EcoGR «Универсал» (на базе «Ecostyle»)",
    "category": "Мобильные туалетные и душевые кабины",
    "description": "Мобильные туалетные и душевые кабины. Туалетные кабины",
    "unit": "шт",
    "basePurchasePrice": 165000,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/istok_audio/tualetnaya_kabina_ecogr_universal_na_baze_ecostyle_.jpg",
    "sourceUrl": "https://www.istok-audio.com/catalog/product/tualetnaya_kabina_ecogr_universal_na_baze_ecostyle_",
    "variantName": "Туалетная кабина EcoGR «Универсал» (на базе «Ecostyle»)",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:06:16+00:00"
  },
  {
    "productId": "prod-safetystep-camokleyashchijsya-rezinovyj-taktilnyj-ugol-protiv-skolzheniya-44-mm",
    "variantId": "var-safetystep-camokleyashchijsya-rezinovyj-taktilnyj-ugol-protiv-skolzheniya-44-mm",
    "supplierId": "sup-safetystep",
    "externalId": "camokleyashchijsya-rezinovyj-taktilnyj-ugol-protiv-skolzheniya-44-mm",
    "sku": "УГОЛ 44ММ",
    "name": "Cамоклеящийся резиновый тактильный угол против скольжения 44 мм",
    "category": "Грязезащитные ковры, дорожки и покрытия",
    "description": "Грязезащитные ковры, дорожки и покрытия. Проступи резиновые накладки на ступень",
    "unit": "шт",
    "basePurchasePrice": 10,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/camokleyashchijsya-rezinovyj-taktilnyj-ugol-protiv-skolzheniya-44-mm.jpg",
    "sourceUrl": "https://www.safetystep.ru/samokleyashchiesya-rezinovye-polosy-i-ugly/camokleyashchijsya-rezinovyj-taktilnyj-ugol-protiv-skolzheniya-44-mm",
    "variantName": "Cамоклеящийся резиновый тактильный угол против скольжения 44 мм",
    "size": "по карточке",
    "color": "по карточке",
    "material": "резина",
    "lastSeenAt": "2026-06-26T10:05:22+00:00"
  },
  {
    "productId": "prod-safetystep-taktilnaya-polimernaya-lenta-so-sfericheskimi-lunkami-lohmann-germaniya",
    "variantId": "var-safetystep-taktilnaya-polimernaya-lenta-so-sfericheskimi-lunkami-lohmann-germaniya",
    "supplierId": "sup-safetystep",
    "externalId": "taktilnaya-polimernaya-lenta-so-sfericheskimi-lunkami-lohmann-germaniya",
    "sku": "DuploTec",
    "name": "Тактильная полимерная лента со сферическими лунками Lohmann Германия",
    "category": "Противоскользящие самоклеящиеся ленты",
    "description": "Противоскользящие самоклеящиеся ленты",
    "unit": "шт",
    "basePurchasePrice": 14,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/taktilnaya-polimernaya-lenta-so-sfericheskimi-lunkami-lohmann-germaniya.jpg",
    "sourceUrl": "https://www.safetystep.ru/protivoskolzyashchie-samokleyashchiesya-lenty/taktilnaya-polimernaya-lenta-so-sfericheskimi-lunkami-lohmann-germaniya",
    "variantName": "Тактильная полимерная лента со сферическими лунками Lohmann Германия",
    "size": "по карточке",
    "color": "по карточке",
    "material": "полимер",
    "lastSeenAt": "2026-06-26T10:05:38+00:00"
  },
  {
    "productId": "prod-safetystep-samokleyashchayasa-rezinovaya-taktilnaya-protivoskolzyashchaya-polosa-29mm",
    "variantId": "var-safetystep-samokleyashchayasa-rezinovaya-taktilnaya-protivoskolzyashchaya-polosa-29mm",
    "supplierId": "sup-safetystep",
    "externalId": "samokleyashchayasa-rezinovaya-taktilnaya-protivoskolzyashchaya-polosa-29mm",
    "sku": "ПОЛОСА 29ММ",
    "name": "Самоклеящаяса резиновая тактильная противоскользящая полоса 29мм",
    "category": "Самоклеящиеся резиновые полосы и углы",
    "description": "Самоклеящиеся резиновые полосы и углы",
    "unit": "шт",
    "basePurchasePrice": 100,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/samokleyashchayasa-rezinovaya-taktilnaya-protivoskolzyashchaya-polosa-29mm.jpg",
    "sourceUrl": "https://www.safetystep.ru/samokleyashchiesya-rezinovye-polosy-i-ugly/samokleyashchayasa-rezinovaya-taktilnaya-protivoskolzyashchaya-polosa-29mm",
    "variantName": "Самоклеящаяса резиновая тактильная противоскользящая полоса 29мм",
    "size": "по карточке",
    "color": "по карточке",
    "material": "резина",
    "lastSeenAt": "2026-06-26T10:05:38+00:00"
  },
  {
    "productId": "prod-safetystep-samokleyashchayasya-rezinovaya-taktilnaya-protivoskolzyashchaya-polosa-50mm",
    "variantId": "var-safetystep-samokleyashchayasya-rezinovaya-taktilnaya-protivoskolzyashchaya-polosa-50mm",
    "supplierId": "sup-safetystep",
    "externalId": "samokleyashchayasya-rezinovaya-taktilnaya-protivoskolzyashchaya-polosa-50mm",
    "sku": "ПОЛОСА 50MM",
    "name": "Самоклеящаяся резиновая тактильная противоскользящая полоса 50мм",
    "category": "Самоклеящиеся резиновые полосы и углы",
    "description": "Самоклеящиеся резиновые полосы и углы",
    "unit": "шт",
    "basePurchasePrice": 160,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/samokleyashchayasya-rezinovaya-taktilnaya-protivoskolzyashchaya-polosa-50mm.jpg",
    "sourceUrl": "https://www.safetystep.ru/samokleyashchiesya-rezinovye-polosy-i-ugly/samokleyashchayasya-rezinovaya-taktilnaya-protivoskolzyashchaya-polosa-50mm",
    "variantName": "Самоклеящаяся резиновая тактильная противоскользящая полоса 50мм",
    "size": "по карточке",
    "color": "по карточке",
    "material": "резина",
    "lastSeenAt": "2026-06-26T10:05:38+00:00"
  },
  {
    "productId": "prod-safetystep-samokleyashchayasya-taktilnaya-lenta-29",
    "variantId": "var-safetystep-samokleyashchayasya-taktilnaya-lenta-29",
    "supplierId": "sup-safetystep",
    "externalId": "samokleyashchayasya-taktilnaya-lenta-29",
    "sku": "ТЛ29",
    "name": "Самоклеящаяся тактильная лента 29",
    "category": "Тактильные ленты, полосы и профили",
    "description": "Тактильные ленты, полосы и профили",
    "unit": "шт",
    "basePurchasePrice": 100,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/samokleyashchayasya-taktilnaya-lenta-29.jpg",
    "sourceUrl": "https://www.safetystep.ru/taktilnie-lenti-polosi-i-profili/samokleyashchayasya-taktilnaya-lenta-29",
    "variantName": "Самоклеящаяся тактильная лента 29",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:05:39+00:00"
  },
  {
    "productId": "prod-safetystep-samokleyashchayasya-taktilnaya-lenta-50",
    "variantId": "var-safetystep-samokleyashchayasya-taktilnaya-lenta-50",
    "supplierId": "sup-safetystep",
    "externalId": "samokleyashchayasya-taktilnaya-lenta-50",
    "sku": "ТЛ50",
    "name": "Самоклеящаяся тактильная лента 50",
    "category": "Тактильные ленты, полосы и профили",
    "description": "Тактильные ленты, полосы и профили",
    "unit": "шт",
    "basePurchasePrice": 160,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/samokleyashchayasya-taktilnaya-lenta-50.jpg",
    "sourceUrl": "https://www.safetystep.ru/taktilnie-lenti-polosi-i-profili/samokleyashchayasya-taktilnaya-lenta-50",
    "variantName": "Самоклеящаяся тактильная лента 50",
    "size": "по карточке",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:05:39+00:00"
  },
  {
    "productId": "prod-safetystep-lenta-protivoskolzyashchaya-abrazivnaya-na-samokleyashchejsya-osnove-zheltaya",
    "variantId": "var-safetystep-lenta-protivoskolzyashchaya-abrazivnaya-na-samokleyashchejsya-osnove-zheltaya",
    "supplierId": "sup-safetystep",
    "externalId": "lenta-protivoskolzyashchaya-abrazivnaya-na-samokleyashchejsya-osnove-zheltaya",
    "sku": "Anti Slip Tape Yellow",
    "name": "Лента противоскользящая абразивная на самоклеящейся основе желтая",
    "category": "Тактильные ленты, полосы и профили",
    "description": "Тактильные ленты, полосы и профили",
    "unit": "шт",
    "basePurchasePrice": 1050,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/lenta-protivoskolzyashchaya-abrazivnaya-na-samokleyashchejsya-osnove-zheltaya.jpg",
    "sourceUrl": "https://www.safetystep.ru/taktilnie-lenti-polosi-i-profili/lenta-protivoskolzyashchaya-abrazivnaya-na-samokleyashchejsya-osnove-zheltaya",
    "variantName": "Лента противоскользящая абразивная на самоклеящейся основе желтая",
    "size": "по карточке",
    "color": "желтый",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:05:39+00:00"
  },
  {
    "productId": "prod-safetystep-nakladka-uglovaya-protivoskolzyashchaya-na-stupen-na-samokleyashchejsya-osnove-44h19mm",
    "variantId": "var-safetystep-nakladka-uglovaya-protivoskolzyashchaya-na-stupen-na-samokleyashchejsya-osnove-44h19mm",
    "supplierId": "sup-safetystep",
    "externalId": "nakladka-uglovaya-protivoskolzyashchaya-na-stupen-na-samokleyashchejsya-osnove-44h19mm",
    "sku": "Угол 44х19",
    "name": "Накладка угловая противоскользящая на ступень на самоклеящейся основе 44х19мм",
    "category": "Тактильные ленты, полосы и профили",
    "description": "Тактильные ленты, полосы и профили",
    "unit": "шт",
    "basePurchasePrice": 200,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/nakladka-uglovaya-protivoskolzyashchaya-na-stupen-na-samokleyashchejsya-osnove-44h19mm.jpg",
    "sourceUrl": "https://www.safetystep.ru/taktilnie-lenti-polosi-i-profili/nakladka-uglovaya-protivoskolzyashchaya-na-stupen-na-samokleyashchejsya-osnove-44h19mm",
    "variantName": "44х19мм",
    "size": "44х19мм",
    "color": "по карточке",
    "material": "по карточке",
    "lastSeenAt": "2026-06-26T10:05:39+00:00"
  },
  {
    "productId": "prod-safetystep-uglovaya-protivoskolzyashchaya-nakladka-na-stupen-v-antivandalnom-alyuminievom-profile",
    "variantId": "var-safetystep-uglovaya-protivoskolzyashchaya-nakladka-na-stupen-v-antivandalnom-alyuminievom-profile",
    "supplierId": "sup-safetystep",
    "externalId": "uglovaya-protivoskolzyashchaya-nakladka-na-stupen-v-antivandalnom-alyuminievom-profile",
    "sku": "Угол 42х16",
    "name": "Угловая противоскользящая накладка на ступень в антивандальном алюминиевом профиле",
    "category": "Тактильные ленты, полосы и профили",
    "description": "Тактильные ленты, полосы и профили",
    "unit": "шт",
    "basePurchasePrice": 225,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/uglovaya-protivoskolzyashchaya-nakladka-na-stupen-v-antivandalnom-alyuminievom-profile.jpg",
    "sourceUrl": "https://www.safetystep.ru/taktilnie-lenti-polosi-i-profili/uglovaya-protivoskolzyashchaya-nakladka-na-stupen-v-antivandalnom-alyuminievom-profile",
    "variantName": "Угловая противоскользящая накладка на ступень в антивандальном алюминиевом профиле",
    "size": "по карточке",
    "color": "по карточке",
    "material": "алюминий",
    "lastSeenAt": "2026-06-26T10:05:39+00:00"
  },
  {
    "productId": "prod-safetystep-lenta-protivoskolzyashchaya-v-antivandalnom-alyuminievom-profile-zheltaya-46-mm-5-mm",
    "variantId": "var-safetystep-lenta-protivoskolzyashchaya-v-antivandalnom-alyuminievom-profile-zheltaya-46-mm-5-mm",
    "supplierId": "sup-safetystep",
    "externalId": "lenta-protivoskolzyashchaya-v-antivandalnom-alyuminievom-profile-zheltaya-46-mm-5-mm",
    "sku": "Полоса 46мм",
    "name": "Лента противоскользящая в антивандальном алюминиевом профиле желтая 46 мм/5 мм",
    "category": "Тактильные ленты, полосы и профили",
    "description": "Тактильные ленты, полосы и профили",
    "unit": "шт",
    "basePurchasePrice": 215,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/lenta-protivoskolzyashchaya-v-antivandalnom-alyuminievom-profile-zheltaya-46-mm-5-mm.jpg",
    "sourceUrl": "https://www.safetystep.ru/taktilnie-lenti-polosi-i-profili/lenta-protivoskolzyashchaya-v-antivandalnom-alyuminievom-profile-zheltaya-46-mm-5-mm",
    "variantName": "Лента противоскользящая в антивандальном алюминиевом профиле желтая 46 мм/5 мм",
    "size": "по карточке",
    "color": "желтый",
    "material": "алюминий",
    "lastSeenAt": "2026-06-26T10:05:39+00:00"
  },
  {
    "productId": "prod-safetystep-uglovaya-protivoskolzyashchaya-nakladka-na-stupen-v-antivandalnom-alyuminievom-profile-s-z",
    "variantId": "var-safetystep-uglovaya-protivoskolzyashchaya-nakladka-na-stupen-v-antivandalnom-alyuminievom-profile-s-z",
    "supplierId": "sup-safetystep",
    "externalId": "uglovaya-protivoskolzyashchaya-nakladka-na-stupen-v-antivandalnom-alyuminievom-profile-s-zheltoj-vstavkoj-80h23",
    "sku": "Угол 80мм",
    "name": "Угловая противоскользящая накладка на ступень в антивандальном алюминиевом профиле с желтой вставкой 80х23",
    "category": "Тактильные ленты, полосы и профили",
    "description": "Тактильные ленты, полосы и профили",
    "unit": "шт",
    "basePurchasePrice": 490,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/uglovaya-protivoskolzyashchaya-nakladka-na-stupen-v-antivandalnom-alyuminievom-profile-s-z.jpg",
    "sourceUrl": "https://www.safetystep.ru/taktilnie-lenti-polosi-i-profili/uglovaya-protivoskolzyashchaya-nakladka-na-stupen-v-antivandalnom-alyuminievom-profile-s-zheltoj-vstavkoj-80h23",
    "variantName": "80х23",
    "size": "80х23",
    "color": "желтый",
    "material": "алюминий",
    "lastSeenAt": "2026-06-26T10:05:39+00:00"
  },
  {
    "productId": "prod-safetystep-taktilmznaya-napravlyaushaya-lenta-50mm",
    "variantId": "var-safetystep-taktilmznaya-napravlyaushaya-lenta-50mm",
    "supplierId": "sup-safetystep",
    "externalId": "taktilmznaya-napravlyaushaya-lenta-50mm",
    "sku": "4591",
    "name": "Тактильная направляющая лента (50 мм) ТЭП на самоклеящейся основе",
    "category": "Тактильные ленты, полосы и профили",
    "description": "Тактильные ленты, полосы и профили",
    "unit": "шт",
    "basePurchasePrice": 160,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/taktilmznaya-napravlyaushaya-lenta-50mm.jpg",
    "sourceUrl": "https://www.safetystep.ru/taktilnie-lenti-polosi-i-profili/taktilmznaya-napravlyaushaya-lenta-50mm",
    "variantName": "Тактильная направляющая лента (50 мм) ТЭП на самоклеящейся основе",
    "size": "по карточке",
    "color": "по карточке",
    "material": "ТЭП",
    "lastSeenAt": "2026-06-26T10:05:39+00:00"
  },
  {
    "productId": "prod-safetystep-taktilnyj-indikator-konus-iz-nerzhaveyushchej-stali-d35-so-shtiftom",
    "variantId": "var-safetystep-taktilnyj-indikator-konus-iz-nerzhaveyushchej-stali-d35-so-shtiftom",
    "supplierId": "sup-safetystep",
    "externalId": "taktilnyj-indikator-konus-iz-nerzhaveyushchej-stali-d35-so-shtiftom",
    "sku": "Индикатор конус D35 AISI 304 со штифтом",
    "name": "Тактильный индикатор конус из нержавеющей стали D35 со штифтом",
    "category": "Тактильные ленты, полосы и профили",
    "description": "Тактильные ленты, полосы и профили",
    "unit": "шт",
    "basePurchasePrice": 33,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/taktilnyj-indikator-konus-iz-nerzhaveyushchej-stali-d35-so-shtiftom.png",
    "sourceUrl": "https://www.safetystep.ru/taktilnie-lenti-polosi-i-profili/taktilnyj-indikator-konus-iz-nerzhaveyushchej-stali-d35-so-shtiftom",
    "variantName": "Тактильный индикатор конус из нержавеющей стали D35 со штифтом",
    "size": "по карточке",
    "color": "по карточке",
    "material": "нержавеющая сталь",
    "lastSeenAt": "2026-06-26T10:05:39+00:00"
  },
  {
    "productId": "prod-safetystep-taktilnyj-indikator-polosa-iz-nerzhaveyushchej-stali-280-h-35-h-15-mm-so-shtiftom",
    "variantId": "var-safetystep-taktilnyj-indikator-polosa-iz-nerzhaveyushchej-stali-280-h-35-h-15-mm-so-shtiftom",
    "supplierId": "sup-safetystep",
    "externalId": "taktilnyj-indikator-polosa-iz-nerzhaveyushchej-stali-280-h-35-h-15-mm-so-shtiftom",
    "sku": "Индикатор полоса 35х280 AISI 304 со штифтом",
    "name": "Тактильный индикатор полоса из нержавеющей стали 280 х 35 х 15 мм со штифтом",
    "category": "Тактильные ленты, полосы и профили",
    "description": "Тактильные ленты, полосы и профили",
    "unit": "шт",
    "basePurchasePrice": 40,
    "availability": "На складе",
    "imageUrl": "/mock/parser-products/safetystep/taktilnyj-indikator-polosa-iz-nerzhaveyushchej-stali-280-h-35-h-15-mm-so-shtiftom.png",
    "sourceUrl": "https://www.safetystep.ru/taktilnie-lenti-polosi-i-profili/taktilnyj-indikator-polosa-iz-nerzhaveyushchej-stali-280-h-35-h-15-mm-so-shtiftom",
    "variantName": "280х35х15мм",
    "size": "280х35х15мм",
    "color": "по карточке",
    "material": "нержавеющая сталь",
    "lastSeenAt": "2026-06-26T10:05:39+00:00"
  },
  {
    "productId": "prod-nepaday-161",
    "variantId": "var-nepaday-161",
    "supplierId": "sup-nepaday",
    "externalId": "161",
    "sku": "161",
    "name": "Уверенный Шаг 50 мм",
    "category": "Закладные профили против скольжения",
    "description": "Крепление: Плиточный клей; Каркас: Алюминий; Вставка: Мягкий эластопласт; Длина: 1,2м; 2,4м; Нагрузка: 2000 шаг/сутки. Закладные профили против скольжения. Крепление: Плиточный клей; Каркас: Алюминий; Вставка: Мягкий эластопласт; Длина: 1,2м; 2,4м",
    "unit": "шт",
    "basePurchasePrice": 640,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/nepaday/161.jpg",
    "sourceUrl": "https://nepaday.ru/index.php?option=com_content&task=view&id=161&Itemid=143",
    "variantName": "1,2м; 2,4м",
    "size": "1,2м; 2,4м",
    "color": "по карточке",
    "material": "Алюминий, Мягкий эластопласт",
    "lastSeenAt": "2026-06-26T10:05:59+00:00"
  },
  {
    "productId": "prod-nepaday-125",
    "variantId": "var-nepaday-125",
    "supplierId": "sup-nepaday",
    "externalId": "125",
    "sku": "125",
    "name": "Safestep 43 мм",
    "category": "Закладные профили против скольжения",
    "description": "Крепление: Плиточный клей; Каркас: Алюминий; Вставка: Мягкий эластопласт; Длина: 1,2м; 2,4м; Нагрузка: 1250 шаг/сутки. Закладные профили против скольжения. Крепление: Плиточный клей; Каркас: Алюминий; Вставка: Мягкий эластопласт; Длина: 1,2м; 2,4м",
    "unit": "шт",
    "basePurchasePrice": 540,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/nepaday/125.jpg",
    "sourceUrl": "https://nepaday.ru/index.php?option=com_content&task=view&id=125&Itemid=105",
    "variantName": "1,2м; 2,4м",
    "size": "1,2м; 2,4м",
    "color": "по карточке",
    "material": "Алюминий, Мягкий эластопласт",
    "lastSeenAt": "2026-06-26T10:05:59+00:00"
  },
  {
    "productId": "prod-nepaday-112",
    "variantId": "var-nepaday-112",
    "supplierId": "sup-nepaday",
    "externalId": "112",
    "sku": "112",
    "name": "ALPB 32 мм",
    "category": "Закладные профили против скольжения",
    "description": "Крепление: Плиточный клей; Каркас: Алюминий; Вставка: ПВХ; Длина: 2,4м; 2,7м; Нагрузка: 1000 шаг/сутки. Закладные профили против скольжения. Крепление: Плиточный клей; Каркас: Алюминий; Вставка: ПВХ; Длина: 2,4м; 2,7м",
    "unit": "шт",
    "basePurchasePrice": 420,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/nepaday/112.jpg",
    "sourceUrl": "https://nepaday.ru/index.php?option=com_content&task=view&id=112&Itemid=104",
    "variantName": "2,4м; 2,7м",
    "size": "2,4м; 2,7м",
    "color": "по карточке",
    "material": "Алюминий, ПВХ",
    "lastSeenAt": "2026-06-26T10:05:59+00:00"
  },
  {
    "productId": "prod-nepaday-494",
    "variantId": "var-nepaday-494",
    "supplierId": "sup-nepaday",
    "externalId": "494",
    "sku": "494",
    "name": "БШ Премиум 50 мм",
    "category": "Закладные профили против скольжения",
    "description": "Крепление: Плиточный клей; Каркас: Бескаркасный; Вставка: Мягкий эластопласт; Длина: 10м; 20м; Нагрузка: 1500 шаг/сутки. Закладные профили против скольжения. Крепление: Плиточный клей; Каркас: Бескаркасный; Вставка: Мягкий эластопласт; Длина: 10м; 20м",
    "unit": "шт",
    "basePurchasePrice": 520,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/nepaday/494.jpg",
    "sourceUrl": "https://nepaday.ru/index.php?option=com_content&task=view&id=494&Itemid=338",
    "variantName": "10м; 20м",
    "size": "10м; 20м",
    "color": "по карточке",
    "material": "Бескаркасный, Мягкий эластопласт",
    "lastSeenAt": "2026-06-26T10:05:59+00:00"
  },
  {
    "productId": "prod-nepaday-493",
    "variantId": "var-nepaday-493",
    "supplierId": "sup-nepaday",
    "externalId": "493",
    "sku": "493",
    "name": "Безопасный шаг 50 мм",
    "category": "Закладные профили против скольжения",
    "description": "Крепление: Плиточный клей; Каркас: Бескаркасный; Вставка: Мягкий эластопласт; Длина: 10м; 20м; Нагрузка: 1000 шаг/сутки. Закладные профили против скольжения. Крепление: Плиточный клей; Каркас: Бескаркасный; Вставка: Мягкий эластопласт; Длина: 10м; 20м",
    "unit": "шт",
    "basePurchasePrice": 390,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/nepaday/493.jpg",
    "sourceUrl": "https://nepaday.ru/index.php?option=com_content&task=view&id=493&Itemid=337",
    "variantName": "10м; 20м",
    "size": "10м; 20м",
    "color": "по карточке",
    "material": "Бескаркасный, Мягкий эластопласт",
    "lastSeenAt": "2026-06-26T10:05:59+00:00"
  },
  {
    "productId": "prod-nepaday-470",
    "variantId": "var-nepaday-470",
    "supplierId": "sup-nepaday",
    "externalId": "470",
    "sku": "470",
    "name": "Эластичные полосы Не Падай",
    "category": "Эластичные полосы и углы из термоэластопластов и резины",
    "description": "Материал: Термоэластопласт; Высота: 2,3 мм - 3,2 мм; Ширина: 29 мм; 40 мм; 50 мм; 80 мм; Цвета: 12 цветов; Крепление: Жидкие гвозди; Нагрузка: до 500 шаг/сут. Эластичные полосы и углы из термоэластопластов и резины. Материал: Термоэластопласт; Высота: 2,3 мм - 3,2 мм; Ширина: 29 мм; 40 мм; 50 мм; 80 мм; Цвета: 12 цветов",
    "unit": "шт",
    "basePurchasePrice": 160,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/nepaday/470.jpg",
    "sourceUrl": "https://nepaday.ru/index.php?option=com_content&task=view&id=470&Itemid=313",
    "variantName": "29 мм; 40 мм; 50 мм; 80 мм",
    "size": "29 мм; 40 мм; 50 мм; 80 мм",
    "color": "по карточке",
    "material": "Термоэластопласт",
    "lastSeenAt": "2026-06-26T10:06:00+00:00"
  },
  {
    "productId": "prod-nepaday-538",
    "variantId": "var-nepaday-538",
    "supplierId": "sup-nepaday",
    "externalId": "538",
    "sku": "538",
    "name": "Эластичные углы Не Падай",
    "category": "Эластичные полосы и углы из термоэластопластов и резины",
    "description": "Материал: Термоэластопласт; Высота: 3,5 мм - 4,2 мм; Ширина: 35 мм; 44 мм; 55 мм; Цвета: 12 цветов; Крепление: Жидкие гвозди; Нагрузка: до 300 шаг/сут. Эластичные полосы и углы из термоэластопластов и резины. Материал: Термоэластопласт; Высота: 3,5 мм - 4,2 мм; Ширина: 35 мм; 44 мм; 55 мм; Цвета: 12 цветов",
    "unit": "шт",
    "basePurchasePrice": 220,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/nepaday/538.jpg",
    "sourceUrl": "https://nepaday.ru/index.php?option=com_content&task=view&id=538&Itemid=386",
    "variantName": "35 мм; 44 мм; 55 мм",
    "size": "35 мм; 44 мм; 55 мм",
    "color": "по карточке",
    "material": "Термоэластопласт",
    "lastSeenAt": "2026-06-26T10:06:00+00:00"
  },
  {
    "productId": "prod-nepaday-379",
    "variantId": "var-nepaday-379",
    "supplierId": "sup-nepaday",
    "externalId": "379",
    "sku": "379",
    "name": "Угол Премиум 50 мм",
    "category": "Накладные профили против скольжения из сырого алюминия",
    "description": "Крепление: Дюбель-гвозди; Каркас: Алюминий; Вставка: Мягкий эластопласт; Длина: 1 м; 1,5 м; 2 м; 3 м; Нагрузка: 750 шаг/сутки. Накладные профили против скольжения из сырого алюминия. Крепление: Дюбель-гвозди; Каркас: Алюминий; Вставка: Мягкий эластопласт; Длина: 1 м; 1,5 м; 2 м; 3 м",
    "unit": "шт",
    "basePurchasePrice": 430,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/nepaday/379.jpg",
    "sourceUrl": "https://nepaday.ru/index.php?option=com_content&task=view&id=379&Itemid=250",
    "variantName": "1 м; 1,5 м; 2 м; 3 м",
    "size": "1 м; 1,5 м; 2 м; 3 м",
    "color": "белый",
    "material": "Алюминий, Мягкий эластопласт",
    "lastSeenAt": "2026-06-26T10:06:00+00:00"
  },
  {
    "productId": "prod-nepaday-162",
    "variantId": "var-nepaday-162",
    "supplierId": "sup-nepaday",
    "externalId": "162",
    "sku": "162",
    "name": "Полоса 100 мм",
    "category": "Накладные профили против скольжения из сырого алюминия",
    "description": "Крепление: Дюбель-гвозди; Каркас: Алюминий; Вставка: Мягкий эластопласт; Длина: 1м; 1,33м; 2м; 3м; Нагрузка: 1500 шаг/сутки. Накладные профили против скольжения из сырого алюминия. Крепление: Дюбель-гвозди; Каркас: Алюминий; Вставка: Мягкий эластопласт; Длина: 1м; 1,33м; 2м; 3м",
    "unit": "шт",
    "basePurchasePrice": 500,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/nepaday/162.jpg",
    "sourceUrl": "https://nepaday.ru/index.php?option=com_content&task=view&id=162&Itemid=147",
    "variantName": "1м; 1,33м; 2м; 3м",
    "size": "1м; 1,33м; 2м; 3м",
    "color": "белый",
    "material": "Алюминий, Мягкий эластопласт",
    "lastSeenAt": "2026-06-26T10:06:00+00:00"
  },
  {
    "productId": "prod-nepaday-395",
    "variantId": "var-nepaday-395",
    "supplierId": "sup-nepaday",
    "externalId": "395",
    "sku": "395",
    "name": "300x300",
    "category": "Тактильная плитка из ПВХ (поливинилхлорид) и ПУ (полиуретан)",
    "description": "300x300 300x300 300x300 300x300 Крепление: Самоклеющиеся; Материал: ПВХ; Риф/База: 4 мм/1 мм; Нагрузка: 500 шаг/сутки. Тактильная плитка из ПВХ (поливинилхлорид) и ПУ (полиуретан). Крепление: Самоклеющиеся; Материал: ПВХ; Риф/База: 4 мм/1 мм; Нагрузка: 500 шаг/сутки",
    "unit": "шт",
    "basePurchasePrice": 320,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/nepaday/395.jpg",
    "sourceUrl": "https://nepaday.ru/index.php?option=com_content&task=view&id=395&Itemid=256",
    "variantName": "300x300",
    "size": "300x300",
    "color": "по карточке",
    "material": "ПВХ",
    "lastSeenAt": "2026-06-26T10:06:06+00:00"
  },
  {
    "productId": "prod-nepaday-545",
    "variantId": "var-nepaday-545",
    "supplierId": "sup-nepaday",
    "externalId": "545",
    "sku": "545",
    "name": "Пандус ПП-50",
    "category": "Приставные пандусы",
    "description": "Материал: Термоэластопласт; Высота: 50 мм; Ширина: 202 мм; Длина: 310 мм; Цвет: 12 цветов; Нагрузка: до 1'500 кг. Приставные пандусы. Материал: Термоэластопласт; Высота: 50 мм; Ширина: 202 мм; Длина: 310 мм",
    "unit": "шт",
    "basePurchasePrice": 1800,
    "availability": "по запросу",
    "imageUrl": "/mock/parser-products/nepaday/545.jpg",
    "sourceUrl": "https://nepaday.ru/index.php?option=com_content&task=view&id=545&Itemid=394",
    "variantName": "310 мм",
    "size": "310 мм",
    "color": "по карточке",
    "material": "Термоэластопласт",
    "lastSeenAt": "2026-06-26T10:06:07+00:00"
  }
]

export const parserMockProducts: SupplierProduct[] = parserMockSeeds.map((item) => ({
  id: item.productId,
  supplierId: item.supplierId,
  externalId: item.externalId,
  sku: item.sku,
  name: item.name,
  category: item.category,
  description: item.description,
  unit: item.unit,
  basePurchasePrice: item.basePurchasePrice,
  currency: 'RUB',
  availability: item.availability,
  lastSeenAt: item.lastSeenAt,
  imageUrl: item.imageUrl,
  sourceUrl: item.sourceUrl,
}))

export const parserMockVariants: ProductVariant[] = parserMockSeeds.map((item) => ({
  id: item.variantId,
  supplierProductId: item.productId,
  variantName: item.variantName,
  size: item.size,
  color: item.color,
  material: item.material,
  sku: item.sku,
  purchasePrice: item.basePurchasePrice,
  availability: item.availability,
  updatedAt: item.lastSeenAt,
}))

export const parserMockPriceHistory: PriceHistory[] = parserMockSeeds.flatMap((item) => {
  const previousPrice = Math.max(1, Math.round(item.basePurchasePrice * 1.04))

  return [
    {
      id: `ph-${item.productId}-prev`,
      supplierProductId: item.productId,
      productVariantId: item.variantId,
      supplierId: item.supplierId,
      purchasePrice: previousPrice,
      currency: 'RUB',
      source: 'parser-mock',
      capturedAt: '2026-06-20T09:00:00.000Z',
    },
    {
      id: `ph-${item.productId}-latest`,
      supplierProductId: item.productId,
      productVariantId: item.variantId,
      supplierId: item.supplierId,
      purchasePrice: item.basePurchasePrice,
      currency: 'RUB',
      source: 'parser-mock',
      capturedAt: item.lastSeenAt.replace('+00:00', '.000Z'),
    },
  ]
})
