import type {
  ActivityLog,
  ContactPerson,
  Counterparty,
  CrmState,
  Deal,
  DocumentRecord,
  Payment,
  TaskRecord,
  WorkObject,
} from './types'
import { verticalMockPriceHistory, verticalMockProducts, verticalMockVariants } from '../lib/verticalMockCatalog'

export const demoTodayIso = '2026-06-22'

interface GeneratedProjectSeed {
  slug: string
  number: string
  counterpartyName: string
  counterpartyShortName: string
  inn: string
  phone: string
  email: string
  contactName: string
  contactPosition: string
  objectName: string
  address: string
  title: string
  description: string
  source: string
  managerId: string
  status: Deal['status']
  objectStatus: WorkObject['status']
  paymentStatus: Payment['status']
  expectedAmount: number
  actualAmount: number
  dueAmount: number
  createdAt: string
  updatedAt: string
  nextActionAt: string
  nextActionText: string
  documentTitles: string[]
}

const generatedProjectSeeds: GeneratedProjectSeed[] = [
  {
    slug: 'bank-ramp',
    number: 'SD-2026-0151',
    counterpartyName: 'АО "Северный банк"',
    counterpartyShortName: 'Северный банк',
    inn: '1658124301',
    phone: '+7 843 210-04-18',
    email: 'facility@northbank.local',
    contactName: 'Лилия Гараева',
    contactPosition: 'Руководитель АХО',
    objectName: 'Центральный офис, входная группа',
    address: 'г. Казань, ул. Баумана, 29',
    title: 'Пандус и контрастная маркировка офиса',
    description: 'Пандус, поручни, кнопка вызова и маркировка стеклянных дверей.',
    source: 'Повторный клиент',
    managerId: 'user-manager-1',
    status: 'negotiation',
    objectStatus: 'quote',
    paymentStatus: 'invoice_not_issued',
    expectedAmount: 426000,
    actualAmount: 0,
    dueAmount: 0,
    createdAt: '2026-06-17T09:10:00.000Z',
    updatedAt: '2026-06-22T08:45:00.000Z',
    nextActionAt: '2026-06-22T14:20:00.000Z',
    nextActionText: 'Получить замечания службы безопасности по схеме входа',
    documentTitles: ['Фото входной группы', 'Черновая схема пандуса'],
  },
  {
    slug: 'kindergarten-entry',
    number: 'SD-2026-0152',
    counterpartyName: 'МБДОУ "Детский сад Радуга"',
    counterpartyShortName: 'Детский сад Радуга',
    inn: '1655032910',
    phone: '+7 843 555-21-44',
    email: 'raduga@edu.local',
    contactName: 'Алсу Хасанова',
    contactPosition: 'Заведующая',
    objectName: 'Главный вход и группа N 4',
    address: 'г. Казань, ул. Фучика, 88',
    title: 'Доступная среда для детского сада',
    description: 'Поручни, тактильные пиктограммы и обновление входного узла.',
    source: 'Муниципальная закупка',
    managerId: 'user-manager-2',
    status: 'quote_ready',
    objectStatus: 'contract',
    paymentStatus: 'overdue',
    expectedAmount: 352000,
    actualAmount: 0,
    dueAmount: 140000,
    createdAt: '2026-06-12T11:40:00.000Z',
    updatedAt: '2026-06-21T16:30:00.000Z',
    nextActionAt: '2026-06-22T13:00:00.000Z',
    nextActionText: 'Напомнить бухгалтерии о просроченном авансе',
    documentTitles: ['Смета по входной группе', 'Письмо с замечаниями'],
  },
  {
    slug: 'factory-navigation',
    number: 'SD-2026-0153',
    counterpartyName: 'ООО "Технопарк Восток"',
    counterpartyShortName: 'Технопарк Восток',
    inn: '1659147742',
    phone: '+7 843 277-90-15',
    email: 'office@techpark-east.local',
    contactName: 'Дмитрий Лапшин',
    contactPosition: 'Главный инженер',
    objectName: 'КПП и маршрут до административного корпуса',
    address: 'г. Казань, ул. Техническая, 12',
    title: 'Навигация и ограждения на промышленной площадке',
    description: 'Маршрут доступности, стойки, поручни и наружные таблички.',
    source: 'Рекомендация',
    managerId: 'user-deputy',
    status: 'contract',
    objectStatus: 'contract',
    paymentStatus: 'partially_paid',
    expectedAmount: 510000,
    actualAmount: 240000,
    dueAmount: 270000,
    createdAt: '2026-06-08T10:05:00.000Z',
    updatedAt: '2026-06-22T09:15:00.000Z',
    nextActionAt: '2026-06-24T10:00:00.000Z',
    nextActionText: 'Согласовать дату поставки стоек и знаков',
    documentTitles: ['Договор поставки', 'Спецификация оборудования'],
  },
  {
    slug: 'pharmacy-chain',
    number: 'SD-2026-0154',
    counterpartyName: 'ООО "Фармплюс"',
    counterpartyShortName: 'Фармплюс',
    inn: '1656014820',
    phone: '+7 843 203-18-70',
    email: 'development@pharmplus.local',
    contactName: 'Вероника Егорова',
    contactPosition: 'Менеджер по развитию',
    objectName: 'Три аптечных филиала',
    address: 'г. Казань, ул. Чистопольская, 34',
    title: 'Таблички и поручни для сети аптек',
    description: 'Единый комплект изделий для трех точек сети.',
    source: 'Заявка с сайта',
    managerId: 'user-manager-1',
    status: 'quote_sent',
    objectStatus: 'quote',
    paymentStatus: 'awaiting_payment',
    expectedAmount: 289000,
    actualAmount: 0,
    dueAmount: 289000,
    createdAt: '2026-06-14T13:25:00.000Z',
    updatedAt: '2026-06-21T10:10:00.000Z',
    nextActionAt: '2026-06-25T12:00:00.000Z',
    nextActionText: 'Получить решение по коммерческому предложению',
    documentTitles: ['КП по трем филиалам'],
  },
  {
    slug: 'sport-center',
    number: 'SD-2026-0155',
    counterpartyName: 'МАУ "Центр спорта Ак Барс"',
    counterpartyShortName: 'Центр спорта Ак Барс',
    inn: '1657041829',
    phone: '+7 843 221-70-44',
    email: 'hoz@akbars-sport.local',
    contactName: 'Ильдар Галимов',
    contactPosition: 'Заместитель директора',
    objectName: 'Раздевалки и входная зона',
    address: 'г. Казань, пр-т Ямашева, 115А',
    title: 'Переоснащение спортивного центра',
    description: 'Поручни, тактильные указатели и комплект пиктограмм.',
    source: 'Плановая модернизация',
    managerId: 'user-manager-2',
    status: 'installation',
    objectStatus: 'installation',
    paymentStatus: 'partially_paid',
    expectedAmount: 612000,
    actualAmount: 360000,
    dueAmount: 252000,
    createdAt: '2026-05-28T15:10:00.000Z',
    updatedAt: '2026-06-22T07:35:00.000Z',
    nextActionAt: '2026-06-23T09:30:00.000Z',
    nextActionText: 'Проверить готовность площадки перед монтажом',
    documentTitles: ['Акт обследования', 'Монтажная схема'],
  },
  {
    slug: 'library',
    number: 'SD-2026-0156',
    counterpartyName: 'МБУК "Городская библиотека"',
    counterpartyShortName: 'Городская библиотека',
    inn: '1654321986',
    phone: '+7 843 299-55-81',
    email: 'info@city-library.local',
    contactName: 'Наталья Морозова',
    contactPosition: 'Заведующая хозяйственной частью',
    objectName: 'Читальный зал и центральный вход',
    address: 'г. Казань, ул. Пушкина, 17',
    title: 'Навигация и таблички библиотеки',
    description: 'Мнемосхема, таблички кабинетов и контрастные указатели.',
    source: 'Письмо заказчика',
    managerId: 'user-manager-1',
    status: 'quote_preparation',
    objectStatus: 'survey',
    paymentStatus: 'overdue',
    expectedAmount: 174000,
    actualAmount: 0,
    dueAmount: 85000,
    createdAt: '2026-06-16T08:45:00.000Z',
    updatedAt: '2026-06-22T09:05:00.000Z',
    nextActionAt: '2026-06-22T17:10:00.000Z',
    nextActionText: 'Уточнить размеры мнемосхемы и закрыть просрочку',
    documentTitles: ['Фото читального зала'],
  },
  {
    slug: 'residential',
    number: 'SD-2026-0157',
    counterpartyName: 'ООО "УК ДомСервис"',
    counterpartyShortName: 'УК ДомСервис',
    inn: '1659182304',
    phone: '+7 843 260-77-42',
    email: 'requests@domservice.local',
    contactName: 'Руслан Закиров',
    contactPosition: 'Инженер по эксплуатации',
    objectName: 'Подъезд N 3, жилой комплекс Солнечный',
    address: 'г. Казань, ул. Аделя Кутуя, 6',
    title: 'Поручни и нескользящие полосы в подъезде',
    description: 'Локальный проект для входной группы жилого дома.',
    source: 'Обращение УК',
    managerId: 'user-manager-2',
    status: 'new',
    objectStatus: 'survey',
    paymentStatus: 'invoice_not_issued',
    expectedAmount: 98000,
    actualAmount: 0,
    dueAmount: 0,
    createdAt: '2026-06-21T12:20:00.000Z',
    updatedAt: '2026-06-21T12:45:00.000Z',
    nextActionAt: '2026-06-23T15:00:00.000Z',
    nextActionText: 'Назначить осмотр подъезда',
    documentTitles: ['Заявка от управляющей компании'],
  },
  {
    slug: 'museum',
    number: 'SD-2026-0158',
    counterpartyName: 'ГБУ "Музей истории города"',
    counterpartyShortName: 'Музей истории',
    inn: '1654027751',
    phone: '+7 843 238-16-90',
    email: 'contract@history-museum.local',
    contactName: 'Екатерина Низамова',
    contactPosition: 'Специалист по закупкам',
    objectName: 'Центральный вход и кассовая зона',
    address: 'г. Казань, Кремль, 2',
    title: 'Доступная среда в музее',
    description: 'Маршрут посетителя, тактильные таблички и поручни.',
    source: 'Госзаказ',
    managerId: 'user-deputy',
    status: 'contract',
    objectStatus: 'contract',
    paymentStatus: 'awaiting_payment',
    expectedAmount: 744000,
    actualAmount: 0,
    dueAmount: 744000,
    createdAt: '2026-06-03T09:25:00.000Z',
    updatedAt: '2026-06-20T18:00:00.000Z',
    nextActionAt: '2026-06-26T11:00:00.000Z',
    nextActionText: 'Передать счет в казначейство заказчика',
    documentTitles: ['Контракт', 'Согласованная спецификация'],
  },
  {
    slug: 'cafe',
    number: 'SD-2026-0159',
    counterpartyName: 'ООО "Кафе Терраса"',
    counterpartyShortName: 'Кафе Терраса',
    inn: '1659203871',
    phone: '+7 843 245-32-17',
    email: 'owner@terrace.local',
    contactName: 'Артем Минин',
    contactPosition: 'Собственник',
    objectName: 'Санузел и входная дверь',
    address: 'г. Казань, ул. Петербургская, 12',
    title: 'Комплект МГН для кафе',
    description: 'Поручни, крючки, пиктограммы и маркировка двери.',
    source: 'Звонок',
    managerId: 'user-manager-1',
    status: 'closed_won',
    objectStatus: 'warranty',
    paymentStatus: 'paid',
    expectedAmount: 132000,
    actualAmount: 132000,
    dueAmount: 0,
    createdAt: '2026-05-22T10:20:00.000Z',
    updatedAt: '2026-06-18T17:30:00.000Z',
    nextActionAt: '2026-07-18T10:00:00.000Z',
    nextActionText: 'Плановая проверка после монтажа',
    documentTitles: ['Акт выполненных работ', 'Фото после монтажа'],
  },
  {
    slug: 'university',
    number: 'SD-2026-0160',
    counterpartyName: 'ФГАОУ "ИТ Университет"',
    counterpartyShortName: 'ИТ Университет',
    inn: '1655001184',
    phone: '+7 843 233-71-04',
    email: 'campus@it-university.local',
    contactName: 'Ренат Ахметов',
    contactPosition: 'Руководитель кампуса',
    objectName: 'Учебный корпус B',
    address: 'г. Иннополис, Университетская, 1',
    title: 'Навигация учебного корпуса',
    description: 'Тактильные указатели, таблички аудиторий и мнемосхемы этажей.',
    source: 'Тендер',
    managerId: 'user-manager-2',
    status: 'in_progress',
    objectStatus: 'installation',
    paymentStatus: 'partially_paid',
    expectedAmount: 890000,
    actualAmount: 420000,
    dueAmount: 120000,
    createdAt: '2026-05-31T11:05:00.000Z',
    updatedAt: '2026-06-22T08:55:00.000Z',
    nextActionAt: '2026-06-27T16:00:00.000Z',
    nextActionText: 'Получить оплату второго этапа',
    documentTitles: ['Этажная схема', 'Счет на второй этап'],
  },
  {
    slug: 'clinic-branch',
    number: 'SD-2026-0161',
    counterpartyName: 'ООО "Медцентр Авиценна"',
    counterpartyShortName: 'Медцентр Авиценна',
    inn: '1658130086',
    phone: '+7 843 266-40-33',
    email: 'supply@avicennamed.local',
    contactName: 'Светлана Курбатова',
    contactPosition: 'Администратор проекта',
    objectName: 'Новый ресепшен клиники',
    address: 'г. Казань, ул. Сибгата Хакима, 50',
    title: 'Оборудование ресепшена клиники',
    description: 'Поручни, таблички, кнопка вызова и контрастная лента.',
    source: 'Партнерская рекомендация',
    managerId: 'user-manager-1',
    status: 'quote_sent',
    objectStatus: 'quote',
    paymentStatus: 'awaiting_payment',
    expectedAmount: 338000,
    actualAmount: 0,
    dueAmount: 338000,
    createdAt: '2026-06-11T14:05:00.000Z',
    updatedAt: '2026-06-21T13:00:00.000Z',
    nextActionAt: '2026-06-24T15:20:00.000Z',
    nextActionText: 'Договориться о встрече с управляющим',
    documentTitles: ['Коммерческое предложение'],
  },
  {
    slug: 'airport-service',
    number: 'SD-2026-0162',
    counterpartyName: 'АО "Аэропорт Казань"',
    counterpartyShortName: 'Аэропорт Казань',
    inn: '1660002847',
    phone: '+7 843 267-88-01',
    email: 'infra@airport-kazan.local',
    contactName: 'Павел Кузнецов',
    contactPosition: 'Начальник службы инфраструктуры',
    objectName: 'Сервисная зона терминала',
    address: 'г. Казань, аэропорт, терминал 1А',
    title: 'Тактильная навигация сервисной зоны',
    description: 'Большой объект с несколькими зонами монтажа и повышенными требованиями допуска.',
    source: 'Корпоративный запрос',
    managerId: 'user-deputy',
    status: 'quote_preparation',
    objectStatus: 'survey',
    paymentStatus: 'invoice_not_issued',
    expectedAmount: 1280000,
    actualAmount: 0,
    dueAmount: 0,
    createdAt: '2026-06-18T08:30:00.000Z',
    updatedAt: '2026-06-22T10:05:00.000Z',
    nextActionAt: '2026-06-25T09:00:00.000Z',
    nextActionText: 'Собрать перечень пропусков для осмотра',
    documentTitles: ['Техническое задание заказчика'],
  },
  {
    slug: 'warehouse',
    number: 'SD-2026-0163',
    counterpartyName: 'ООО "Волга Логистик"',
    counterpartyShortName: 'Волга Логистик',
    inn: '1657178200',
    phone: '+7 843 250-90-64',
    email: 'warehouse@volgalogistic.local',
    contactName: 'Ольга Шумилова',
    contactPosition: 'Руководитель склада',
    objectName: 'Зона отгрузки и офис склада',
    address: 'г. Казань, ул. Магистральная, 100',
    title: 'Ограждения и маркировка склада',
    description: 'Поручни, сигнальная разметка и защитные элементы.',
    source: 'Холодный звонок',
    managerId: 'user-manager-2',
    status: 'awaiting_payment',
    objectStatus: 'contract',
    paymentStatus: 'awaiting_payment',
    expectedAmount: 470000,
    actualAmount: 0,
    dueAmount: 260000,
    createdAt: '2026-06-06T16:15:00.000Z',
    updatedAt: '2026-06-20T11:00:00.000Z',
    nextActionAt: '2026-06-28T10:00:00.000Z',
    nextActionText: 'Контроль оплаты авансового счета',
    documentTitles: ['Счет на аванс', 'Спецификация склада'],
  },
  {
    slug: 'hotel-conference',
    number: 'SD-2026-0164',
    counterpartyName: 'ООО "Отель Парус"',
    counterpartyShortName: 'Отель Парус',
    inn: '1659100208',
    phone: '+7 843 260-22-10',
    email: 'admin@parus-hotel.local',
    contactName: 'Мария Одинцова',
    contactPosition: 'Управляющая',
    objectName: 'Конференц-зал и холл второго этажа',
    address: 'г. Казань, ул. Право-Булачная, 33',
    title: 'Доступная навигация отеля',
    description: 'Таблички, пиктограммы и поручни для конференц-зоны.',
    source: 'Повторная продажа',
    managerId: 'user-manager-1',
    status: 'quote_ready',
    objectStatus: 'quote',
    paymentStatus: 'invoice_not_issued',
    expectedAmount: 221000,
    actualAmount: 0,
    dueAmount: 0,
    createdAt: '2026-06-19T11:50:00.000Z',
    updatedAt: '2026-06-22T09:45:00.000Z',
    nextActionAt: '2026-06-23T16:10:00.000Z',
    nextActionText: 'Отправить финальную версию КП управляющей',
    documentTitles: ['План второго этажа'],
  },
  {
    slug: 'lyceum-yard',
    number: 'SD-2026-0165',
    counterpartyName: 'МАОУ "Лицей N 4"',
    counterpartyShortName: 'Лицей N 4',
    inn: '1654048927',
    phone: '+7 843 533-42-91',
    email: 'school4@edu.local',
    contactName: 'Гульнара Фатхутдинова',
    contactPosition: 'Директор',
    objectName: 'Вход со двора и лестничный марш',
    address: 'г. Казань, ул. Гвардейская, 54',
    title: 'Монтаж поручней во дворе лицея',
    description: 'Внешние поручни, контрастные полосы и таблички входа.',
    source: 'Муниципальный план',
    managerId: 'user-manager-2',
    status: 'installation',
    objectStatus: 'installation',
    paymentStatus: 'partially_paid',
    expectedAmount: 390000,
    actualAmount: 210000,
    dueAmount: 180000,
    createdAt: '2026-06-01T09:55:00.000Z',
    updatedAt: '2026-06-22T07:20:00.000Z',
    nextActionAt: '2026-06-23T08:40:00.000Z',
    nextActionText: 'Проверить поставку внешних поручней',
    documentTitles: ['Монтажная ведомость'],
  },
  {
    slug: 'mfc-east',
    number: 'SD-2026-0166',
    counterpartyName: 'ГАУ "МФЦ Восточный"',
    counterpartyShortName: 'МФЦ Восточный',
    inn: '1659007701',
    phone: '+7 843 222-06-18',
    email: 'office@mfc-east.local',
    contactName: 'Елена Сафонова',
    contactPosition: 'Администратор здания',
    objectName: 'Окна приема и зал ожидания',
    address: 'г. Казань, ул. Минская, 12',
    title: 'Тактильная навигация МФЦ',
    description: 'Таблички, мнемосхема и маркировка пути до окон приема.',
    source: 'Входящий запрос',
    managerId: 'user-deputy',
    status: 'negotiation',
    objectStatus: 'quote',
    paymentStatus: 'invoice_not_issued',
    expectedAmount: 575000,
    actualAmount: 0,
    dueAmount: 0,
    createdAt: '2026-06-13T08:20:00.000Z',
    updatedAt: '2026-06-21T18:25:00.000Z',
    nextActionAt: '2026-06-24T10:45:00.000Z',
    nextActionText: 'Согласовать скидку и сроки поставки',
    documentTitles: ['Запрос коммерческого предложения'],
  },
  {
    slug: 'theater',
    number: 'SD-2026-0167',
    counterpartyName: 'ГАУК "Театр Молодежный"',
    counterpartyShortName: 'Театр Молодежный',
    inn: '1653088120',
    phone: '+7 843 292-18-30',
    email: 'hoz@moltheater.local',
    contactName: 'Валерий Сомов',
    contactPosition: 'Заведующий постановочной частью',
    objectName: 'Кассовая зона и вход в партер',
    address: 'г. Казань, ул. Островского, 10',
    title: 'Таблички и поручни театра',
    description: 'Маркировка кассовой зоны, входа в зал и санитарного узла.',
    source: 'План капитального ремонта',
    managerId: 'user-manager-1',
    status: 'quote_preparation',
    objectStatus: 'survey',
    paymentStatus: 'overdue',
    expectedAmount: 315000,
    actualAmount: 0,
    dueAmount: 90000,
    createdAt: '2026-06-15T12:35:00.000Z',
    updatedAt: '2026-06-22T08:25:00.000Z',
    nextActionAt: '2026-06-22T15:40:00.000Z',
    nextActionText: 'Закрыть просрочку по предварительному счету',
    documentTitles: ['Фото кассовой зоны'],
  },
  {
    slug: 'biotest-lab',
    number: 'SD-2026-0168',
    counterpartyName: 'ООО "Биотест Лаборатория"',
    counterpartyShortName: 'Биотест',
    inn: '1656137740',
    phone: '+7 843 245-77-30',
    email: 'lab@biotest.local',
    contactName: 'Сергей Матвеев',
    contactPosition: 'Коммерческий директор',
    objectName: 'Входная группа лаборатории',
    address: 'г. Казань, ул. Академика Глушко, 8',
    title: 'Входная группа лаборатории',
    description: 'Комплект поручней, тактильные указатели и кнопка вызова.',
    source: 'Заявка партнера',
    managerId: 'user-manager-2',
    status: 'closed_lost',
    objectStatus: 'closed',
    paymentStatus: 'invoice_not_issued',
    expectedAmount: 205000,
    actualAmount: 0,
    dueAmount: 0,
    createdAt: '2026-05-20T13:15:00.000Z',
    updatedAt: '2026-06-10T14:30:00.000Z',
    nextActionAt: '2026-07-10T10:00:00.000Z',
    nextActionText: 'Вернуться к клиенту после смены бюджета',
    documentTitles: ['Отказ по бюджету'],
  },
]

const generatedProjectCounterparties: Counterparty[] = generatedProjectSeeds.map((seed, index) => ({
  id: `cp-${seed.slug}`,
  type: 'organization',
  name: seed.counterpartyName,
  shortName: seed.counterpartyShortName,
  inn: seed.inn,
  kpp: seed.inn ? `${seed.inn.slice(0, 4)}01001` : '',
  ogrn: seed.inn ? `10${seed.inn}00${index}` : '',
  phone: seed.phone,
  email: seed.email,
  website: '',
  legalAddress: seed.address,
  actualAddress: seed.address,
  comment: seed.description,
  responsibleUserId: seed.managerId,
  status: seed.status === 'closed_lost' ? 'paused' : 'active',
  createdAt: seed.createdAt,
  updatedAt: seed.updatedAt,
}))

const generatedProjectContacts: ContactPerson[] = generatedProjectSeeds.map((seed) => ({
  id: `contact-${seed.slug}-main`,
  counterpartyId: `cp-${seed.slug}`,
  fullName: seed.contactName,
  position: seed.contactPosition,
  phone: seed.phone,
  email: seed.email,
  messenger: 'Telegram',
  comment: 'Основной контакт по проекту.',
  isPrimary: true,
}))

const generatedProjectObjects: WorkObject[] = generatedProjectSeeds.map((seed, index) => ({
  id: `obj-${seed.slug}`,
  counterpartyId: `cp-${seed.slug}`,
  name: seed.objectName,
  address: seed.address,
  geoLat: 55.75 + index * 0.003,
  geoLng: 49.1 + index * 0.004,
  responsibleManagerId: seed.managerId,
  assignedInstallerId: 'user-installer',
  status: seed.objectStatus,
  comment: seed.description,
  importantNotes: seed.nextActionText,
  createdAt: seed.createdAt,
  updatedAt: seed.updatedAt,
}))

const generatedProjectDeals: Deal[] = generatedProjectSeeds.map((seed) => ({
  id: `deal-${seed.slug}`,
  number: seed.number,
  counterpartyId: `cp-${seed.slug}`,
  objectId: `obj-${seed.slug}`,
  responsibleUserId: seed.managerId,
  status: seed.status,
  paymentStatus: seed.paymentStatus,
  title: seed.title,
  description: seed.description,
  source: seed.source,
  expectedAmount: seed.expectedAmount,
  actualAmount: seed.actualAmount,
  nextActionText: seed.nextActionText,
  nextActionAt: seed.nextActionAt,
  createdAt: seed.createdAt,
  updatedAt: seed.updatedAt,
  closedAt: seed.status === 'closed_won' || seed.status === 'closed_lost' ? seed.updatedAt : null,
}))

const generatedProjectPayments: Payment[] = generatedProjectSeeds
  .filter((seed) => seed.dueAmount > 0 || seed.actualAmount > 0 || seed.paymentStatus === 'paid')
  .map((seed, index) => {
    const amountTotal = seed.dueAmount + seed.actualAmount

    return {
      id: `pay-${seed.slug}`,
      counterpartyId: `cp-${seed.slug}`,
      dealId: `deal-${seed.slug}`,
      invoiceDocumentId: null,
      responsibleUserId: 'user-accountant',
      status: seed.paymentStatus,
      invoiceNumber: `СЧ-2026-${String(90 + index).padStart(3, '0')}`,
      invoiceDate: seed.paymentStatus === 'overdue' ? '2026-06-10' : '2026-06-18',
      expectedPaymentDate: seed.paymentStatus === 'overdue' ? '2026-06-18' : '2026-06-28',
      paidAt: seed.paymentStatus === 'paid' ? '2026-06-18' : seed.actualAmount > 0 ? '2026-06-14' : null,
      amountTotal,
      amountPaid: seed.actualAmount,
      amountDue: seed.dueAmount,
      currency: 'RUB',
      comment: seed.paymentStatus === 'overdue' ? 'Просрочка видна в общем реестре и карточке.' : 'Платеж связан с проектом.',
      createdAt: seed.updatedAt,
      updatedAt: seed.updatedAt,
    }
  })

const generatedProjectDocuments: DocumentRecord[] = generatedProjectSeeds.flatMap((seed) =>
  seed.documentTitles.map((title, index) => ({
    id: `doc-${seed.slug}-${index + 1}`,
    counterpartyId: `cp-${seed.slug}`,
    objectId: `obj-${seed.slug}`,
    dealId: `deal-${seed.slug}`,
    paymentId: null,
    quoteId: null,
    uploadedByUserId: seed.managerId,
    type: index % 2 === 0 ? 'specification' : 'drawing',
    title,
    originalFilename: `${seed.number}-${index + 1}.pdf`,
    demoPath: `/demo-docs/${seed.slug}/${seed.number}-${index + 1}.pdf`,
    mimeType: 'application/pdf',
    sizeBytes: 620000 + index * 210000,
    hash: `generated-${seed.slug}-${index + 1}`,
    status: 'active',
    comment: 'Документ привязан к контрагенту, объекту и проекту.',
    createdAt: seed.updatedAt,
    updatedAt: seed.updatedAt,
  })),
)

const generatedProjectTasks: TaskRecord[] = generatedProjectSeeds
  .filter((seed) => seed.status !== 'closed_won')
  .map((seed) => ({
    id: `task-${seed.slug}`,
    title: seed.nextActionText,
    description: `${seed.number} · ${seed.title}`,
    type: seed.paymentStatus === 'overdue' ? 'payment_reminder' : 'quote_follow_up',
    status: seed.status === 'closed_lost' ? 'done' : 'open',
    priority: seed.paymentStatus === 'overdue' ? 'urgent' : 'normal',
    dueAt: seed.nextActionAt,
    assignedToUserId: seed.paymentStatus === 'overdue' ? 'user-accountant' : seed.managerId,
    createdByUserId: 'user-director',
    counterpartyId: `cp-${seed.slug}`,
    dealId: `deal-${seed.slug}`,
    objectId: `obj-${seed.slug}`,
    paymentId: seed.dueAmount > 0 || seed.actualAmount > 0 ? `pay-${seed.slug}` : null,
    createdAt: seed.updatedAt,
    updatedAt: seed.updatedAt,
    closedAt: seed.status === 'closed_lost' ? seed.updatedAt : null,
  }))

const generatedProjectActivity: ActivityLog[] = generatedProjectSeeds.map((seed) => ({
  id: `act-${seed.slug}`,
  actorUserId: seed.managerId,
  entityType: 'deal',
  entityId: `deal-${seed.slug}`,
  action: 'deal.updated',
  title: `Обновлен проект ${seed.number}`,
  details: seed.nextActionText,
  createdAt: seed.updatedAt,
}))

export const seedCrmState: CrmState = {
  version: 1,
  currentUserId: 'user-director',
  roles: [
    {
      id: 'role-admin',
      code: 'admin',
      name: 'Администратор',
      summary: 'Пользователи, роли, настройки демки и полный доступ к данным.',
      permissions: ['users.manage', 'crm.read_all', 'crm.write_all', 'finance.write', 'settings.manage'],
    },
    {
      id: 'role-director',
      code: 'director',
      name: 'Руководитель',
      summary: 'Видит всю операционную картину, финансы, аналитику и историю.',
      permissions: ['crm.read_all', 'crm.write_all', 'finance.read', 'analytics.full'],
    },
    {
      id: 'role-deputy',
      code: 'deputy_director',
      name: 'Заместитель директора',
      summary: 'Коммерческий контроль сделок, КП, менеджеров и поставщиков.',
      permissions: ['crm.read_all', 'deals.manage', 'quotes.manage', 'catalog.manage', 'analytics.full'],
    },
    {
      id: 'role-manager',
      code: 'manager',
      name: 'Менеджер',
      summary: 'Контрагенты, объекты, сделки, КП и каталог в пределах коммерческой работы.',
      permissions: ['counterparties.write', 'deals.write', 'quotes.write', 'catalog.read', 'purchase_price.read'],
    },
    {
      id: 'role-accountant',
      code: 'accountant',
      name: 'Бухгалтер',
      summary: 'Счета, оплаты, документы, закрывающие акты и платежная аналитика.',
      permissions: ['documents.write', 'payments.write', 'finance.read', 'analytics.payments'],
    },
    {
      id: 'role-installer',
      code: 'installer',
      name: 'Монтажник',
      summary: 'Назначенные объекты, фото, замеры и офлайн-заметки.',
      permissions: ['objects.assigned_read', 'installer_notes.write', 'documents.photo_write'],
    },
    {
      id: 'role-office',
      code: 'office_user',
      name: 'Офисный сотрудник',
      summary: 'Ограниченная работа с карточками, вложениями и заполненностью базы.',
      permissions: ['counterparties.read_limited', 'documents.write_limited', 'tasks.read'],
    },
  ],
  users: [
    {
      id: 'user-admin',
      fullName: 'Илья Администратор',
      email: 'admin@uchet-system.local',
      phone: '+7 987 000-00-01',
      username: 'admin',
      roleCode: 'admin',
      isActive: true,
      lastLoginAt: '2026-06-22T08:40:00.000Z',
    },
    {
      id: 'user-director',
      fullName: 'Илья Кайнов',
      email: 'director@uchet-system.local',
      phone: '+7 987 747-16-07',
      username: 'ikaynov',
      roleCode: 'director',
      isActive: true,
      lastLoginAt: '2026-06-22T09:05:00.000Z',
    },
    {
      id: 'user-deputy',
      fullName: 'Андрей Кравцов',
      email: 'deputy@uchet-system.local',
      phone: '+7 987 211-44-20',
      username: 'akravtsov',
      roleCode: 'deputy_director',
      isActive: true,
      lastLoginAt: '2026-06-21T17:48:00.000Z',
    },
    {
      id: 'user-manager-1',
      fullName: 'Марина Смирнова',
      email: 'm.smirnova@uchet-system.local',
      phone: '+7 987 122-33-44',
      username: 'msmirnova',
      roleCode: 'manager',
      isActive: true,
      lastLoginAt: '2026-06-22T09:12:00.000Z',
    },
    {
      id: 'user-manager-2',
      fullName: 'Денис Галеев',
      email: 'd.galeev@uchet-system.local',
      phone: '+7 987 455-66-77',
      username: 'dgaleev',
      roleCode: 'manager',
      isActive: true,
      lastLoginAt: '2026-06-22T08:58:00.000Z',
    },
    {
      id: 'user-accountant',
      fullName: 'Елена Фролова',
      email: 'accounting@uchet-system.local',
      phone: '+7 987 300-22-11',
      username: 'efrolova',
      roleCode: 'accountant',
      isActive: true,
      lastLoginAt: '2026-06-22T08:52:00.000Z',
    },
    {
      id: 'user-installer',
      fullName: 'Сергей Монтажников',
      email: 'installer@uchet-system.local',
      phone: '+7 987 744-10-12',
      username: 'sinstaller',
      roleCode: 'installer',
      isActive: true,
      lastLoginAt: '2026-06-21T19:14:00.000Z',
    },
    {
      id: 'user-office',
      fullName: 'Наталья Орлова',
      email: 'office@uchet-system.local',
      phone: '+7 987 900-41-00',
      username: 'norlovа',
      roleCode: 'office_user',
      isActive: true,
      lastLoginAt: '2026-06-20T16:03:00.000Z',
    },
  ],
  counterparties: [
    {
      id: 'cp-clinic',
      type: 'organization',
      name: 'ГБУЗ "Городская клиника N 7"',
      shortName: 'Клиника N 7',
      inn: '1657009402',
      kpp: '165701001',
      ogrn: '1021602854410',
      phone: '+7 843 244-18-10',
      email: 'zakupki@clinic7.local',
      website: 'clinic7.example.ru',
      legalAddress: '420111, г. Казань, ул. Лесная, 18',
      actualAddress: 'г. Казань, ул. Лесная, 18',
      comment: 'Муниципальный заказчик, просит закрыть входную группу до проверки.',
      responsibleUserId: 'user-manager-1',
      status: 'active',
      createdAt: '2026-03-11T10:20:00.000Z',
      updatedAt: '2026-06-21T12:12:00.000Z',
    },
    {
      id: 'cp-school',
      type: 'organization',
      name: 'МАОУ "Учебный корпус N 12"',
      shortName: 'Учебный корпус N 12',
      inn: '1654775191',
      kpp: '165401001',
      ogrn: '1041622113200',
      phone: '+7 843 510-12-44',
      email: 'director@school12.local',
      website: '',
      legalAddress: '420073, г. Казань, пр-т Победы, 44',
      actualAddress: 'г. Казань, пр-т Победы, 44',
      comment: 'Нужен маршрут доступности и маркировка к началу учебного года.',
      responsibleUserId: 'user-manager-2',
      status: 'active',
      createdAt: '2026-04-02T09:10:00.000Z',
      updatedAt: '2026-06-20T15:18:00.000Z',
    },
    {
      id: 'cp-mall',
      type: 'organization',
      name: 'ООО "ТЦ Северный"',
      shortName: 'ТЦ Северный',
      inn: '1660812555',
      kpp: '166001001',
      ogrn: '1161690145819',
      phone: '+7 843 700-80-90',
      email: 'office@sever-mall.local',
      website: 'sever-mall.example.ru',
      legalAddress: '420029, г. Казань, ул. Центральная, 7',
      actualAddress: 'г. Казань, ул. Центральная, 7',
      comment: 'Коммерческий объект, согласуют смету через управляющую компанию.',
      responsibleUserId: 'user-deputy',
      status: 'lead',
      createdAt: '2026-05-18T14:05:00.000Z',
      updatedAt: '2026-06-22T07:55:00.000Z',
    },
    {
      id: 'cp-admin',
      type: 'organization',
      name: 'Администрация Вахитовского района',
      shortName: 'Администрация района',
      inn: '1652101008',
      kpp: '165201001',
      ogrn: '1021602833001',
      phone: '+7 843 299-10-01',
      email: 'docs@vahitov.local',
      website: 'vahitov.example.ru',
      legalAddress: '420111, г. Казань, пл. Советская, 1',
      actualAddress: 'г. Казань, пл. Советская, 1',
      comment: 'Есть большой архив документов за прошлые годы, импортировать через шаблон.',
      responsibleUserId: 'user-accountant',
      status: 'paused',
      createdAt: '2026-02-16T11:45:00.000Z',
      updatedAt: '2026-06-18T13:28:00.000Z',
    },
    {
      id: 'cp-hotel',
      type: 'organization',
      name: 'ООО "Отель Волга"',
      shortName: 'Отель Волга',
      inn: '',
      kpp: '',
      ogrn: '',
      phone: '',
      email: 'reception@volga-hotel.local',
      website: '',
      legalAddress: '',
      actualAddress: 'г. Казань, ул. Кремлевская, 4',
      comment: 'Нужно дозаполнить реквизиты перед договором.',
      responsibleUserId: 'user-manager-1',
      status: 'lead',
      createdAt: '2026-06-12T16:22:00.000Z',
      updatedAt: '2026-06-22T09:00:00.000Z',
    },
    ...generatedProjectCounterparties,
  ],
  contacts: [
    {
      id: 'contact-clinic-main',
      counterpartyId: 'cp-clinic',
      fullName: 'Ирина Павлова',
      position: 'Заместитель главврача по АХЧ',
      phone: '+7 917 240-66-10',
      email: 'pavlova@clinic7.local',
      messenger: 'Telegram',
      comment: 'Просит короткие статусы по WhatsApp после каждого этапа.',
      isPrimary: true,
    },
    {
      id: 'contact-school-main',
      counterpartyId: 'cp-school',
      fullName: 'Рамиль Сафин',
      position: 'Директор',
      phone: '+7 917 500-12-44',
      email: 'safin@school12.local',
      messenger: 'WhatsApp',
      comment: 'Согласует счет после утверждения схемы.',
      isPrimary: true,
    },
    {
      id: 'contact-mall-main',
      counterpartyId: 'cp-mall',
      fullName: 'Анна Климова',
      position: 'Управляющий объектом',
      phone: '+7 917 889-18-01',
      email: 'klimova@sever-mall.local',
      messenger: 'Telegram',
      comment: 'Ждет выездной осмотр по санузлу.',
      isPrimary: true,
    },
    {
      id: 'contact-admin-main',
      counterpartyId: 'cp-admin',
      fullName: 'Виктор Осипов',
      position: 'Главный специалист отдела закупок',
      phone: '+7 843 299-10-44',
      email: 'osipov@vahitov.local',
      messenger: 'Email',
      comment: 'Передаст архив договоров через Excel-реестр.',
      isPrimary: true,
    },
    ...generatedProjectContacts,
  ],
  objects: [
    {
      id: 'obj-clinic-entry',
      counterpartyId: 'cp-clinic',
      name: 'Входная группа поликлиники',
      address: 'г. Казань, ул. Лесная, 18, центральный вход',
      geoLat: 55.796,
      geoLng: 49.112,
      responsibleManagerId: 'user-manager-1',
      assignedInstallerId: 'user-installer',
      status: 'quote',
      comment: 'Пандус, поручни, кнопка вызова, контрастная маркировка.',
      importantNotes: 'Проверка доступности назначена на 28.06.2026.',
      createdAt: '2026-03-12T08:55:00.000Z',
      updatedAt: '2026-06-21T12:08:00.000Z',
    },
    {
      id: 'obj-clinic-floor',
      counterpartyId: 'cp-clinic',
      name: 'Первый этаж и регистратура',
      address: 'г. Казань, ул. Лесная, 18, 1 этаж',
      geoLat: 55.796,
      geoLng: 49.112,
      responsibleManagerId: 'user-manager-1',
      assignedInstallerId: 'user-installer',
      status: 'survey',
      comment: 'Нужны тактильные указатели и таблички.',
      importantNotes: 'Осмотр без остановки приема пациентов.',
      createdAt: '2026-05-29T12:35:00.000Z',
      updatedAt: '2026-06-19T09:40:00.000Z',
    },
    {
      id: 'obj-school-route',
      counterpartyId: 'cp-school',
      name: 'Маршрут доступности от входа до кабинетов',
      address: 'г. Казань, пр-т Победы, 44',
      geoLat: 55.768,
      geoLng: 49.206,
      responsibleManagerId: 'user-manager-2',
      assignedInstallerId: 'user-installer',
      status: 'contract',
      comment: 'Тактильная плитка, контрастная лента, таблички.',
      importantNotes: 'Монтаж только после 15:00.',
      createdAt: '2026-04-03T10:05:00.000Z',
      updatedAt: '2026-06-20T15:22:00.000Z',
    },
    {
      id: 'obj-mall-wc',
      counterpartyId: 'cp-mall',
      name: 'Санузел МГН на первом этаже',
      address: 'г. Казань, ул. Центральная, 7, блок B',
      geoLat: 55.787,
      geoLng: 49.147,
      responsibleManagerId: 'user-deputy',
      assignedInstallerId: 'user-installer',
      status: 'survey',
      comment: 'Нужны поручни, откидное сиденье, схема размещения.',
      importantNotes: 'Уточнить материал стен до финальной сметы.',
      createdAt: '2026-05-18T14:45:00.000Z',
      updatedAt: '2026-06-22T07:50:00.000Z',
    },
    {
      id: 'obj-admin-archive',
      counterpartyId: 'cp-admin',
      name: 'Архив договоров и актов',
      address: 'г. Казань, пл. Советская, 1',
      geoLat: null,
      geoLng: null,
      responsibleManagerId: 'user-accountant',
      assignedInstallerId: 'user-installer',
      status: 'closed',
      comment: 'Объект для привязки исторических документов.',
      importantNotes: 'Не выполнять ручной перенос архива за клиента.',
      createdAt: '2026-02-16T12:00:00.000Z',
      updatedAt: '2026-06-18T13:29:00.000Z',
    },
    {
      id: 'obj-hotel-lobby',
      counterpartyId: 'cp-hotel',
      name: 'Лобби и входная зона',
      address: 'г. Казань, ул. Кремлевская, 4',
      geoLat: 55.795,
      geoLng: 49.108,
      responsibleManagerId: 'user-manager-1',
      assignedInstallerId: 'user-installer',
      status: 'survey',
      comment: 'Первичный лид, реквизиты не заполнены.',
      importantNotes: 'Перед КП запросить ИНН и телефон ответственного.',
      createdAt: '2026-06-12T16:30:00.000Z',
      updatedAt: '2026-06-22T09:01:00.000Z',
    },
    ...generatedProjectObjects,
  ],
  deals: [
    {
      id: 'deal-clinic-entry',
      number: 'SD-2026-0142',
      counterpartyId: 'cp-clinic',
      objectId: 'obj-clinic-entry',
      responsibleUserId: 'user-manager-1',
      status: 'quote_preparation',
      paymentStatus: 'overdue',
      title: 'Доступная входная группа',
      description: 'Комплект оборудования и монтаж для центрального входа клиники.',
      source: 'Повторное обращение',
      expectedAmount: 482000,
      actualAmount: 0,
      nextActionText: 'Согласовать обновленное КП и закрыть просроченный счет',
      nextActionAt: '2026-06-22T15:00:00.000Z',
      createdAt: '2026-06-10T09:30:00.000Z',
      updatedAt: '2026-06-22T08:10:00.000Z',
      closedAt: null,
    },
    {
      id: 'deal-school-route',
      number: 'SD-2026-0131',
      counterpartyId: 'cp-school',
      objectId: 'obj-school-route',
      responsibleUserId: 'user-manager-2',
      status: 'quote_sent',
      paymentStatus: 'awaiting_payment',
      title: 'Маршрут доступности',
      description: 'Тактильные указатели, контрастная маркировка и таблички.',
      source: 'Рекомендация',
      expectedAmount: 315000,
      actualAmount: 0,
      nextActionText: 'Дождаться решения по цене и выставить счет',
      nextActionAt: '2026-06-24T11:00:00.000Z',
      createdAt: '2026-05-29T13:10:00.000Z',
      updatedAt: '2026-06-20T15:18:00.000Z',
      closedAt: null,
    },
    {
      id: 'deal-mall-wc',
      number: 'SD-2026-0148',
      counterpartyId: 'cp-mall',
      objectId: 'obj-mall-wc',
      responsibleUserId: 'user-deputy',
      status: 'new',
      paymentStatus: 'invoice_not_issued',
      title: 'Санузел МГН',
      description: 'Смета после выездного осмотра, нужна схема креплений.',
      source: 'Заявка с сайта',
      expectedAmount: 268000,
      actualAmount: 0,
      nextActionText: 'Назначить монтажника на осмотр',
      nextActionAt: '2026-06-23T10:30:00.000Z',
      createdAt: '2026-06-21T16:00:00.000Z',
      updatedAt: '2026-06-22T07:55:00.000Z',
      closedAt: null,
    },
    {
      id: 'deal-clinic-floor',
      number: 'SD-2026-0128',
      counterpartyId: 'cp-clinic',
      objectId: 'obj-clinic-floor',
      responsibleUserId: 'user-manager-1',
      status: 'in_progress',
      paymentStatus: 'partially_paid',
      title: 'Навигация первого этажа',
      description: 'Тактильные указатели, мнемосхемы и информационные таблички.',
      source: 'Дополнительная потребность',
      expectedAmount: 198000,
      actualAmount: 98000,
      nextActionText: 'Получить вторую оплату перед монтажом',
      nextActionAt: '2026-06-25T14:00:00.000Z',
      createdAt: '2026-05-30T11:05:00.000Z',
      updatedAt: '2026-06-21T12:15:00.000Z',
      closedAt: null,
    },
    {
      id: 'deal-admin-archive',
      number: 'SD-2026-0090',
      counterpartyId: 'cp-admin',
      objectId: 'obj-admin-archive',
      responsibleUserId: 'user-accountant',
      status: 'in_progress',
      paymentStatus: 'paid',
      title: 'Архив договоров 2020-2024',
      description: 'Структурирование старых документов через импорт-реестр.',
      source: 'Внутренняя задача',
      expectedAmount: 0,
      actualAmount: 0,
      nextActionText: 'Дождаться Excel-реестра от заказчика',
      nextActionAt: '2026-06-30T12:00:00.000Z',
      createdAt: '2026-02-17T09:00:00.000Z',
      updatedAt: '2026-06-18T13:29:00.000Z',
      closedAt: null,
    },
    {
      id: 'deal-hotel-lobby',
      number: 'SD-2026-0150',
      counterpartyId: 'cp-hotel',
      objectId: 'obj-hotel-lobby',
      responsibleUserId: 'user-manager-1',
      status: 'new',
      paymentStatus: 'invoice_not_issued',
      title: 'Входная зона отеля',
      description: 'Первичная заявка на КП, реквизиты неполные.',
      source: 'Звонок',
      expectedAmount: 156000,
      actualAmount: 0,
      nextActionText: 'Дозаполнить телефон и ИНН перед КП',
      nextActionAt: '2026-06-22T16:20:00.000Z',
      createdAt: '2026-06-22T09:00:00.000Z',
      updatedAt: '2026-06-22T09:00:00.000Z',
      closedAt: null,
    },
    ...generatedProjectDeals,
  ],
  suppliers: [
    {
      id: 'sup-vertical',
      name: 'Вертикаль',
      code: 'vertical',
      sourceType: 'site_catalog',
      isActive: true,
      lastUpdatedAt: '2026-06-22T06:20:00.000Z',
      updateStatus: 'fresh',
      updateNote: 'Мок-каталог из локального парсера: 50 отобранных позиций.',
    },
    {
      id: 'sup-access',
      name: 'Доступная среда Комплект',
      code: 'access-kit',
      sourceType: 'excel',
      isActive: true,
      lastUpdatedAt: '2026-06-21T18:30:00.000Z',
      updateStatus: 'fresh',
      updateNote: 'Загружен Excel-прайс, ошибок 0.',
    },
    {
      id: 'sup-med',
      name: 'Медтехника Поволжье',
      code: 'med-volga',
      sourceType: 'manual',
      isActive: true,
      lastUpdatedAt: '2026-06-20T11:10:00.000Z',
      updateStatus: 'needs_check',
      updateNote: 'Обновлены поручни, 8 позиций требуют ручной проверки.',
    },
    {
      id: 'sup-city',
      name: 'Городские решения',
      code: 'city-solutions',
      sourceType: 'site_catalog',
      isActive: true,
      lastUpdatedAt: '2026-06-22T06:34:00.000Z',
      updateStatus: 'outdated',
      updateNote: 'Прайс требует ручной проверки, старая версия каталога сохранена.',
    },
    {
      id: 'sup-signs',
      name: 'Тактильные таблички РФ',
      code: 'tactile-signs',
      sourceType: 'site_catalog',
      isActive: true,
      lastUpdatedAt: '2026-06-22T06:28:00.000Z',
      updateStatus: 'fresh',
      updateNote: 'Демо-прайс обновлен: 328 позиций.',
    },
    {
      id: 'sup-local',
      name: 'Локальный склад',
      code: 'local-stock',
      sourceType: 'manual',
      isActive: true,
      lastUpdatedAt: '2026-06-19T09:00:00.000Z',
      updateStatus: 'needs_check',
      updateNote: 'Ручное обновление остатков менеджером.',
    },
  ],
  products: verticalMockProducts,
  variants: verticalMockVariants,
  priceHistory: verticalMockPriceHistory,
  quotes: [
    {
      id: 'quote-clinic-entry',
      number: 'КП-146-В',
      dealId: 'deal-clinic-entry',
      counterpartyId: 'cp-clinic',
      objectId: 'obj-clinic-entry',
      createdByUserId: 'user-manager-1',
      status: 'draft',
      title: 'КП на доступную входную группу',
      introText: 'Подбор оборудования по результатам осмотра объекта.',
      termsText: 'Срок действия КП 10 дней. Доставка включена.',
      subtotalPurchase: 230800,
      subtotalSale: 329900,
      discountAmount: 0,
      totalSale: 329900,
      currency: 'RUB',
      exportedDocPath: '',
      createdAt: '2026-06-21T12:00:00.000Z',
      updatedAt: '2026-06-22T08:10:00.000Z',
      sentAt: null,
      items: [
        {
          id: 'qi-clinic-handrail',
          quoteId: 'quote-clinic-entry',
          supplierId: 'sup-vertical',
          supplierProductId: 'prod-handrail-vertical',
          productVariantId: 'var-handrail-vertical-900',
          name: 'Поручень настенный для МГН',
          sku: 'VR-PN-38-900',
          size: '900 мм',
          color: 'нержавейка',
          unit: 'шт',
          qty: 6,
          purchasePrice: 18500,
          salePrice: 24900,
          comment: 'Snapshot цены из каталога на 22.06.',
          sortOrder: 1,
        },
        {
          id: 'qi-clinic-ramp',
          quoteId: 'quote-clinic-entry',
          supplierId: 'sup-access',
          supplierProductId: 'prod-ramp-access',
          productVariantId: 'var-ramp-access-1200',
          name: 'Пандус модульный алюминиевый',
          sku: 'DS-RMP-1200',
          size: '1200 мм',
          color: 'алюминий',
          unit: 'секц.',
          qty: 2,
          purchasePrice: 64200,
          salePrice: 88400,
          comment: 'Excel-прайс поставщика.',
          sortOrder: 2,
        },
        {
          id: 'qi-clinic-call',
          quoteId: 'quote-clinic-entry',
          supplierId: 'sup-local',
          supplierProductId: 'prod-call-button',
          productVariantId: 'var-call-button-ip65',
          name: 'Кнопка вызова помощи IP65',
          sku: 'LS-CALL-IP65',
          size: 'комплект',
          color: 'синий',
          unit: 'компл.',
          qty: 1,
          purchasePrice: 11800,
          salePrice: 17900,
          comment: 'На складе.',
          sortOrder: 3,
        },
      ],
    },
    {
      id: 'quote-school-route',
      number: 'КП-138-В',
      dealId: 'deal-school-route',
      counterpartyId: 'cp-school',
      objectId: 'obj-school-route',
      createdByUserId: 'user-manager-2',
      status: 'sent',
      title: 'КП на маршрут доступности',
      introText: 'Комплект материалов для маршрута от входа до кабинетов.',
      termsText: 'Срок поставки 7 рабочих дней после оплаты.',
      subtotalPurchase: 114400,
      subtotalSale: 181500,
      discountAmount: 0,
      totalSale: 181500,
      currency: 'RUB',
      exportedDocPath: '/documents/КП-138-В.pdf',
      createdAt: '2026-06-18T10:00:00.000Z',
      updatedAt: '2026-06-19T17:30:00.000Z',
      sentAt: '2026-06-19T17:30:00.000Z',
      items: [
        {
          id: 'qi-school-tile',
          quoteId: 'quote-school-route',
          supplierId: 'sup-access',
          supplierProductId: 'prod-tactile-access',
          productVariantId: 'var-tactile-access-yellow',
          name: 'Тактильная плитка желтая 300x300',
          sku: 'DS-TILE-Y-300',
          size: '300x300',
          color: 'желтый',
          unit: 'шт',
          qty: 120,
          purchasePrice: 690,
          salePrice: 1120,
          comment: 'Цена из Excel-прайса.',
          sortOrder: 1,
        },
        {
          id: 'qi-school-tape',
          quoteId: 'quote-school-route',
          supplierId: 'sup-access',
          supplierProductId: 'prod-contrast-tape',
          productVariantId: 'var-contrast-tape-50',
          name: 'Контрастная лента противоскользящая',
          sku: 'DS-TAPE-50',
          size: '50 мм x 18 м',
          color: 'желто-черный',
          unit: 'рул.',
          qty: 14,
          purchasePrice: 980,
          salePrice: 1640,
          comment: 'Для ступеней и стеклянных дверей.',
          sortOrder: 2,
        },
      ],
    },
  ],
  documents: [
    {
      id: 'doc-clinic-contract',
      counterpartyId: 'cp-clinic',
      objectId: 'obj-clinic-entry',
      dealId: 'deal-clinic-entry',
      paymentId: 'pay-clinic-overdue',
      quoteId: null,
      uploadedByUserId: 'user-accountant',
      type: 'contract',
      title: 'Договор поставки 2024',
      originalFilename: 'Договор_ГБУЗ_Клиника_2024.docx',
      demoPath: '/demo-docs/clinic/Договор_2024.docx',
      mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      sizeBytes: 1830000,
      hash: 'docx-001',
      status: 'active',
      comment: 'Открывается во внешнем Word.',
      createdAt: '2026-06-10T12:30:00.000Z',
      updatedAt: '2026-06-10T12:30:00.000Z',
    },
    {
      id: 'doc-clinic-plan',
      counterpartyId: 'cp-clinic',
      objectId: 'obj-clinic-entry',
      dealId: 'deal-clinic-entry',
      paymentId: null,
      quoteId: null,
      uploadedByUserId: 'user-installer',
      type: 'drawing',
      title: 'Чертеж входной группы',
      originalFilename: 'plan_entry.pdf',
      demoPath: '/demo-docs/clinic/plan_entry.pdf',
      mimeType: 'application/pdf',
      sizeBytes: 6400000,
      hash: 'pdf-002',
      status: 'active',
      comment: 'PDF можно смотреть внутри программы.',
      createdAt: '2026-06-18T09:45:00.000Z',
      updatedAt: '2026-06-18T09:45:00.000Z',
    },
    {
      id: 'doc-clinic-photo',
      counterpartyId: 'cp-clinic',
      objectId: 'obj-clinic-entry',
      dealId: 'deal-clinic-entry',
      paymentId: null,
      quoteId: null,
      uploadedByUserId: 'user-installer',
      type: 'photo',
      title: 'Фото объекта после осмотра',
      originalFilename: 'entry_photo_01.jpg',
      demoPath: '/demo-docs/clinic/entry_photo_01.jpg',
      mimeType: 'image/jpeg',
      sizeBytes: 3200000,
      hash: 'img-003',
      status: 'active',
      comment: 'Фото из демо-сценария монтажника.',
      createdAt: '2026-06-18T09:48:00.000Z',
      updatedAt: '2026-06-18T09:48:00.000Z',
    },
    {
      id: 'doc-school-quote',
      counterpartyId: 'cp-school',
      objectId: 'obj-school-route',
      dealId: 'deal-school-route',
      paymentId: null,
      quoteId: 'quote-school-route',
      uploadedByUserId: 'user-manager-2',
      type: 'quote',
      title: 'КП-138-В по маршруту доступности',
      originalFilename: 'КП-138-В.pdf',
      demoPath: '/demo-docs/school/КП-138-В.pdf',
      mimeType: 'application/pdf',
      sizeBytes: 820000,
      hash: 'pdf-004',
      status: 'active',
      comment: 'Экспортировано из КП-конструктора.',
      createdAt: '2026-06-19T17:31:00.000Z',
      updatedAt: '2026-06-19T17:31:00.000Z',
    },
    {
      id: 'doc-mall-request',
      counterpartyId: 'cp-mall',
      objectId: 'obj-mall-wc',
      dealId: 'deal-mall-wc',
      paymentId: null,
      quoteId: null,
      uploadedByUserId: 'user-office',
      type: 'other',
      title: 'Первичная заявка ТЦ',
      originalFilename: 'request_wc.xlsx',
      demoPath: '/demo-docs/mall/request_wc.xlsx',
      mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      sizeBytes: 460000,
      hash: 'xlsx-005',
      status: 'needs_review',
      comment: 'XLSX хранится и открывается внешней программой.',
      createdAt: '2026-06-21T16:04:00.000Z',
      updatedAt: '2026-06-21T16:04:00.000Z',
    },
    {
      id: 'doc-admin-archive',
      counterpartyId: 'cp-admin',
      objectId: 'obj-admin-archive',
      dealId: 'deal-admin-archive',
      paymentId: null,
      quoteId: null,
      uploadedByUserId: 'user-accountant',
      type: 'other',
      title: 'Реестр договоров 2020-2024',
      originalFilename: 'archive_registry_2020_2024.xlsx',
      demoPath: '/demo-docs/admin/archive_registry_2020_2024.xlsx',
      mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      sizeBytes: 42000000,
      hash: 'xlsx-006',
      status: 'needs_review',
      comment: 'Большой Excel-реестр для будущего заполнения мок-данными.',
      createdAt: '2026-06-18T13:20:00.000Z',
      updatedAt: '2026-06-18T13:20:00.000Z',
    },
    ...generatedProjectDocuments,
  ],
  payments: [
    {
      id: 'pay-clinic-overdue',
      counterpartyId: 'cp-clinic',
      dealId: 'deal-clinic-entry',
      invoiceDocumentId: 'doc-clinic-contract',
      responsibleUserId: 'user-accountant',
      status: 'overdue',
      invoiceNumber: 'СЧ-2026-071',
      invoiceDate: '2026-06-12',
      expectedPaymentDate: '2026-06-17',
      paidAt: null,
      amountTotal: 190000,
      amountPaid: 0,
      amountDue: 190000,
      currency: 'RUB',
      comment: 'Просрочка видна в карточке контрагента и сделки.',
      createdAt: '2026-06-12T12:35:00.000Z',
      updatedAt: '2026-06-22T06:05:00.000Z',
    },
    {
      id: 'pay-school-awaiting',
      counterpartyId: 'cp-school',
      dealId: 'deal-school-route',
      invoiceDocumentId: null,
      responsibleUserId: 'user-accountant',
      status: 'awaiting_payment',
      invoiceNumber: 'СЧ-2026-076',
      invoiceDate: '2026-06-20',
      expectedPaymentDate: '2026-06-27',
      paidAt: null,
      amountTotal: 315000,
      amountPaid: 0,
      amountDue: 315000,
      currency: 'RUB',
      comment: 'Ожидаем оплату после решения по КП.',
      createdAt: '2026-06-20T15:30:00.000Z',
      updatedAt: '2026-06-20T15:30:00.000Z',
    },
    {
      id: 'pay-clinic-partial',
      counterpartyId: 'cp-clinic',
      dealId: 'deal-clinic-floor',
      invoiceDocumentId: null,
      responsibleUserId: 'user-accountant',
      status: 'partially_paid',
      invoiceNumber: 'СЧ-2026-064',
      invoiceDate: '2026-06-02',
      expectedPaymentDate: '2026-06-25',
      paidAt: '2026-06-08',
      amountTotal: 198000,
      amountPaid: 98000,
      amountDue: 100000,
      currency: 'RUB',
      comment: 'Остаток перед монтажом.',
      createdAt: '2026-06-02T14:00:00.000Z',
      updatedAt: '2026-06-08T10:00:00.000Z',
    },
    {
      id: 'pay-admin-paid',
      counterpartyId: 'cp-admin',
      dealId: 'deal-admin-archive',
      invoiceDocumentId: null,
      responsibleUserId: 'user-accountant',
      status: 'paid',
      invoiceNumber: 'СЧ-2026-031',
      invoiceDate: '2026-03-01',
      expectedPaymentDate: '2026-03-14',
      paidAt: '2026-03-12',
      amountTotal: 72000,
      amountPaid: 72000,
      amountDue: 0,
      currency: 'RUB',
      comment: 'Оплачено полностью.',
      createdAt: '2026-03-01T11:00:00.000Z',
      updatedAt: '2026-03-12T16:00:00.000Z',
    },
    ...generatedProjectPayments,
  ],
  tasks: [
    {
      id: 'task-clinic-payment',
      title: 'Позвонить по просроченному счету',
      description: 'СЧ-2026-071 просрочен с 17.06. Уточнить дату оплаты.',
      type: 'payment_reminder',
      status: 'open',
      priority: 'urgent',
      dueAt: '2026-06-22T12:00:00.000Z',
      assignedToUserId: 'user-accountant',
      createdByUserId: 'user-director',
      counterpartyId: 'cp-clinic',
      dealId: 'deal-clinic-entry',
      objectId: 'obj-clinic-entry',
      paymentId: 'pay-clinic-overdue',
      createdAt: '2026-06-22T06:05:00.000Z',
      updatedAt: '2026-06-22T06:05:00.000Z',
      closedAt: null,
    },
    {
      id: 'task-mall-survey',
      title: 'Выездной осмотр санузла МГН',
      description: 'Сделать фото стен, замерить расстояния и проверить крепления.',
      type: 'manual',
      status: 'in_progress',
      priority: 'high',
      dueAt: '2026-06-23T10:30:00.000Z',
      assignedToUserId: 'user-installer',
      createdByUserId: 'user-deputy',
      counterpartyId: 'cp-mall',
      dealId: 'deal-mall-wc',
      objectId: 'obj-mall-wc',
      paymentId: null,
      createdAt: '2026-06-22T07:58:00.000Z',
      updatedAt: '2026-06-22T07:58:00.000Z',
      closedAt: null,
    },
    {
      id: 'task-hotel-data',
      title: 'Дозаполнить реквизиты отеля',
      description: 'Нет телефона и ИНН, нельзя выпускать договор.',
      type: 'fill_missing_data',
      status: 'open',
      priority: 'normal',
      dueAt: '2026-06-22T16:20:00.000Z',
      assignedToUserId: 'user-manager-1',
      createdByUserId: 'user-manager-1',
      counterpartyId: 'cp-hotel',
      dealId: 'deal-hotel-lobby',
      objectId: 'obj-hotel-lobby',
      paymentId: null,
      createdAt: '2026-06-22T09:02:00.000Z',
      updatedAt: '2026-06-22T09:02:00.000Z',
      closedAt: null,
    },
    {
      id: 'task-catalog-city',
      title: 'Проверить прайс поставщика',
      description: 'Городские решения изменили каталог. Предыдущий демо-прайс сохранен.',
      type: 'catalog_update_check',
      status: 'open',
      priority: 'high',
      dueAt: '2026-06-22T17:00:00.000Z',
      assignedToUserId: 'user-deputy',
      createdByUserId: 'user-admin',
      counterpartyId: null,
      dealId: null,
      objectId: null,
      paymentId: null,
      createdAt: '2026-06-22T06:36:00.000Z',
      updatedAt: '2026-06-22T06:36:00.000Z',
      closedAt: null,
    },
    ...generatedProjectTasks,
  ],
  installerNotes: [
    {
      id: 'note-clinic-offline',
      objectId: 'obj-clinic-entry',
      dealId: 'deal-clinic-entry',
      installerUserId: 'user-installer',
      text: 'Демо-осмотр входной группы: нужен вынос крепления поручня на 60 мм.',
      measurements: [
        { label: 'Ширина прохода', value: '1820 мм' },
        { label: 'Перепад высоты', value: '145 мм' },
      ],
      localClientId: 'local-note-20260618-01',
      status: 'local_draft',
      createdOfflineAt: '2026-06-18T09:45:00.000Z',
      createdAt: '2026-06-18T09:45:00.000Z',
      updatedAt: '2026-06-18T09:45:00.000Z',
    },
    {
      id: 'note-school-saved',
      objectId: 'obj-school-route',
      dealId: 'deal-school-route',
      installerUserId: 'user-installer',
      text: 'Уточнение по лестничному маршу: 11 ступеней, нужна контрастная маркировка.',
      measurements: [
        { label: 'Ступени', value: '11 шт' },
        { label: 'Ширина марша', value: '1560 мм' },
      ],
      localClientId: 'local-note-20260617-02',
      status: 'saved',
      createdOfflineAt: '2026-06-17T15:20:00.000Z',
      createdAt: '2026-06-17T15:20:00.000Z',
      updatedAt: '2026-06-17T17:40:00.000Z',
    },
  ],
  activity: [
    {
      id: 'act-manager-clinic-quote-updated',
      actorUserId: 'user-manager-1',
      entityType: 'quote',
      entityId: 'quote-clinic-entry',
      action: 'quote.draft_updated',
      title: 'Черновик КП по клинике обновлен',
      details: 'Марина добавила позиции по поручням и оставила КП в работе до проверки цены.',
      createdAt: '2026-06-22T09:36:00.000Z',
    },
    {
      id: 'act-manager-hotel-request',
      actorUserId: 'user-manager-1',
      entityType: 'deal',
      entityId: 'deal-hotel-lobby',
      action: 'deal.data_requested',
      title: 'Запрошены реквизиты по отелю',
      details: 'Клиенту отправлен список недостающих данных перед подготовкой КП.',
      createdAt: '2026-06-22T09:18:00.000Z',
    },
    {
      id: 'act-director-risks-reviewed',
      actorUserId: 'user-director',
      entityType: 'deal',
      entityId: 'deal-clinic-entry',
      action: 'deal.risk_reviewed',
      title: 'Проверены риски по просроченному счету',
      details: 'Руководитель отметил проект клиники для контроля оплаты и согласования КП.',
      createdAt: '2026-06-22T09:10:00.000Z',
    },
    {
      id: 'act-payment-overdue',
      actorUserId: 'user-accountant',
      entityType: 'payment',
      entityId: 'pay-clinic-overdue',
      action: 'payment.overdue',
      title: 'Счет СЧ-2026-071 стал просроченным',
      details: 'Остаток 190 000 руб., ожидаемая дата 17.06.2026.',
      createdAt: '2026-06-22T06:05:00.000Z',
    },
    {
      id: 'act-catalog-failed',
      actorUserId: 'user-admin',
      entityType: 'supplier',
      entityId: 'sup-city',
      action: 'catalog.needs_check',
      title: 'Прайс Городские решения требует проверки',
      details: 'Предыдущая версия каталога сохранена в демо-данных, создана задача проверки.',
      createdAt: '2026-06-22T06:36:00.000Z',
    },
    {
      id: 'act-quote-sent',
      actorUserId: 'user-manager-2',
      entityType: 'quote',
      entityId: 'quote-school-route',
      action: 'quote.exported',
      title: 'КП-138-В экспортировано и отправлено',
      details: 'PDF привязан к сделке SD-2026-0131.',
      createdAt: '2026-06-19T17:31:00.000Z',
    },
    {
      id: 'act-document-uploaded',
      actorUserId: 'user-installer',
      entityType: 'document',
      entityId: 'doc-clinic-photo',
      action: 'document.uploaded',
      title: 'Фото объекта добавлено из осмотра монтажника',
      details: 'Файл entry_photo_01.jpg привязан к объекту входной группы.',
      createdAt: '2026-06-18T09:48:00.000Z',
    },
    ...generatedProjectActivity,
  ],
  analyticsMonths: [
    { month: 'Янв', deals: 11, quotes: 9, payments: 720000, overdue: 90000 },
    { month: 'Фев', deals: 14, quotes: 12, payments: 940000, overdue: 60000 },
    { month: 'Мар', deals: 17, quotes: 13, payments: 1130000, overdue: 45000 },
    { month: 'Апр', deals: 15, quotes: 14, payments: 1010000, overdue: 110000 },
    { month: 'Май', deals: 19, quotes: 16, payments: 1380000, overdue: 72000 },
    { month: 'Июн', deals: 12, quotes: 10, payments: 820000, overdue: 190000 },
  ],
}
